# Elementary/Middle T1 21/22 Old-New Similarity Check

In [1]:
import pandas as pd
import os

In [2]:
old = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\rt_fisher_data.xlsx", sheet_name="TK-5")

In [3]:
old.head()

School Grade Level  Student ID Gender  \
0  Berkeley Arts Magnet Elementary School           K     2020428      F   
1  Berkeley Arts Magnet Elementary School           K     2020105      F   
2  Berkeley Arts Magnet Elementary School           K     2020091      F   
3  Berkeley Arts Magnet Elementary School           K     2020130      M   
4  Berkeley Arts Magnet Elementary School           K     2020653      M   

  Reported Race Student Is Special Ed? 504 English Proficiency Language  \
0         White                      N   N                  EO      NaN   
1        Latinx                      N   N                  EO      NaN   
2         White                      N   N                  EO      NaN   
3         White                      N   N                  EO      NaN   
4         White                      N   N                  EO      NaN   

  SED from CALPADS  ...     Year  Trimester  Vision Scholars  \
0                N  ...  2021-22          1              NaN   
1                N  ...  2021-22          1              NaN   
2                N  ...  2021-22          1              NaN   
3                N  ...  2021-22          1              NaN   
4                N  ...  2021-22          1              NaN   

  Writing On Demand STAR Reading State BC Name  STAR Math State BC Name  \
0               NaN                         NaN                     NaN   
1               NaN                         NaN                     NaN   
2               NaN                         NaN                     NaN   
3               NaN                         NaN                     NaN   
4               NaN                         NaN                     NaN   

   Spanish Math  District BCL  Spanish Math District Benchmark Name  \
0                         NaN                                   NaN   
1                         NaN                                   NaN   
2                         NaN                                   NaN   
3                         NaN                                   NaN   
4                         NaN                                   NaN   

   Spanish Math Percentile Rank Spanish Math Scaled Score  
0                           NaN                       NaN  
1                           NaN                       NaN  
2                           NaN                       NaN  
3                           NaN                       NaN  
4                           NaN                       NaN  

[5 rows x 47 columns]

In [4]:
old_cols = old.columns.to_list()

In [5]:
old_cols

['School',
 'Grade Level',
 'Student ID',
 'Gender',
 'Reported Race',
 'Student Is Special Ed?',
 504,
 'English Proficiency',
 'Language',
 'SED from CALPADS',
 'McKV/ Homeless',
 'Suspensions through 10/25',
 'Attendance through 10/15',
 'Report Card: English TCRWP',
 'Report Card: English TCRWP level',
 'Report Card: Spanish TCRWP',
 'Report Card: Spanish TCRWP level',
 'Report Card: Op & Alg Thinking',
 'Report Card: Num & Ops in Base Ten',
 'Report Card: Measurement and Data',
 'Report Card: Geometry',
 'Report Card: Math Fluency',
 'STAR Reading District BC Name',
 'STAR Reading Instructional Reading Level',
 'STAR Reading Scaled Score',
 'STAR Math Spanish?',
 'STAR Math District BC Name',
 'STAR Math Percentile Rank',
 'STAR Math Scaled Score',
 'IDEL Instructional Level',
 'Dibels Composite Score',
 'Dibels Composite Level',
 'Math Benchmark Percent Correct',
 'Math Benchmark Performance Level',
 'Teacher',
 'Last Name',
 'First Name',
 'Year',
 'Trimester',
 'Vision Scholars

In [6]:
new = old = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\Elementary_Middle T1 21_22.xlsx", sheet_name="Sheet1")

In [7]:
new.head()

School Grade Level         Teacher  \
0  Berkeley Arts Magnet Elementary School           K  Stroik, Sophia   
1  Berkeley Arts Magnet Elementary School           K  Stroik, Sophia   
2  Berkeley Arts Magnet Elementary School           K  Stroik, Sophia   
3  Berkeley Arts Magnet Elementary School           K  Stroik, Sophia   
4  Berkeley Arts Magnet Elementary School           K  Stroik, Sophia   

   Student ID  Last Name First Name Gender Reported Race  \
0   2020428.0    Adelman     Margot      F         White   
1   2020105.0   Andrizzi    Liliana      F        Latinx   
2   2020091.0     Arnold        Aya      F         White   
3   2020130.0     Benton    Charles      M         White   
4   2020653.0  Berkowitz       Levi      M         White   

  Student Is Special Ed? 504.0  ... STAR Reading Scaled Score  \
0                      N     N  ...                       NaN   
1                      N     N  ...                       NaN   
2                      N     N  ...                       NaN   
3                      N     N  ...                       NaN   
4                      N     N  ...                       NaN   

  STAR Math Spanish? STAR Math District BC Name STAR Math Percentile Rank  \
0                NaN                        NaN                       NaN   
1                NaN                        NaN                       NaN   
2                NaN                        NaN                       NaN   
3                NaN                        NaN                       NaN   
4                NaN                        NaN                       NaN   

   STAR Math Scaled Score  IDEL Instructional Level Dibels Composite Score  \
0                     NaN                       NaN                  327.0   
1                     NaN                       NaN                  275.0   
2                     NaN                       NaN                  302.0   
3                     NaN                       NaN                  328.0   
4                     NaN                       NaN                  332.0   

   Dibels Composite Level Math Benchmark Percent Correct  \
0            At Benchmark                          86.67   
1    Well Below Benchmark                             40   
2         Below Benchmark                          86.67   
3            At Benchmark                            100   
4         Above Benchmark                          86.67   

   Math Benchmark Performance Level  
0                      Consistently  
1                            Rarely  
2                      Consistently  
3                      Consistently  
4                      Consistently  

[5 rows x 37 columns]

In [8]:
new_cols = new.columns.to_list()

In [9]:
new_cols

['School',
 'Grade Level',
 'Teacher',
 'Student ID',
 'Last Name',
 'First Name',
 'Gender',
 'Reported Race',
 'Student Is Special Ed?',
 504.0,
 'English Proficiency',
 'Language',
 'SED from CALPADS',
 'McKV/ Homeless',
 'Suspensions through 10/25',
 'Attendance through 10/15',
 'Report Card: English TCRWP',
 'Report Card: English TCRWP level',
 'Report Card: Spanish TCRWP',
 'Report Card: Spanish TCRWP level',
 'Report Card: Op & Alg Thinking',
 'Report Card: Num & Ops in Base Ten',
 'Report Card: Measurement and Data',
 'Report Card: Geometry',
 'Report Card: Math Fluency',
 'STAR Reading District BC Name',
 'STAR Reading Instructional Reading Level',
 'STAR Reading Scaled Score',
 'STAR Math Spanish?',
 'STAR Math District BC Name',
 'STAR Math Percentile Rank',
 'STAR Math Scaled Score',
 'IDEL Instructional Level',
 'Dibels Composite Score',
 'Dibels Composite Level',
 'Math Benchmark Percent Correct',
 'Math Benchmark Performance Level']

In [10]:
len(old_cols)

47

In [11]:
len(new_cols)

37

In [12]:
i=0
for index, col in enumerate(old_cols):
    if col in new_cols:
        i+=1
        #print(f"col {index} of old data is in the new data")

In [13]:
i

37

In [14]:
i=0
for index, col in enumerate(old_cols):
    if col in new_cols:
        i+=1
        print(f"col {index} of old data is in the new data")

col 0 of old data is in the new data
col 1 of old data is in the new data
col 2 of old data is in the new data
col 3 of old data is in the new data
col 4 of old data is in the new data
col 5 of old data is in the new data
col 6 of old data is in the new data
col 7 of old data is in the new data
col 8 of old data is in the new data
col 9 of old data is in the new data
col 10 of old data is in the new data
col 11 of old data is in the new data
col 12 of old data is in the new data
col 13 of old data is in the new data
col 14 of old data is in the new data
col 15 of old data is in the new data
col 16 of old data is in the new data
col 17 of old data is in the new data
col 18 of old data is in the new data
col 19 of old data is in the new data
col 20 of old data is in the new data
col 21 of old data is in the new data
col 22 of old data is in the new data
col 23 of old data is in the new data
col 24 of old data is in the new data
col 25 of old data is in the new data
col 26 of old data is 

## T2 21-22 (Elementary)

In [15]:
new_t2 = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\21_22 Data Sheets TK-12 RT.xlsx", sheet_name="Elementary T2")

In [16]:
new_t2.head()

School Grade Level             Teacher  \
0  Thousand Oaks Elementary School         5.0    Gillis, Jennifer   
1      John Muir Elementary School         5.0     Rosenthal, Lisa   
2       Cragmont Elementary School          KG        Rosen, Adria   
3       Cragmont Elementary School         2.0  Herbertson, Janine   
4      John Muir Elementary School         5.0     Rosenthal, Lisa   

   Student ID       Last Name First Name Gender Reported Race  \
0   2013206.0           Abbas   Muhammad      M         Asian   
1   2010668.0  Abcarian-Scott    Anahita      F        Latinx   
2   2020100.0        Abdallah     Shatha      F         White   
3   2016531.0        Abdallah     Shayma      F         White   
4   2018595.0    Abdel Rahman      Asser      M         White   

  Student Is Special Ed?     504.0  ... STAR Math Spanish?  \
0                    NaN       NaN  ...                NaN   
1                      Y  504 Plan  ...                NaN   
2                    NaN       NaN  ...                NaN   
3                    NaN       NaN  ...                NaN   
4                    NaN       NaN  ...                NaN   

  Spanish Math  District BCL Spanish Math District Benchmark Name  \
0                        NaN                                  NaN   
1                        NaN                                  NaN   
2                        NaN                                  NaN   
3                        NaN                                  NaN   
4                        NaN                                  NaN   

  Spanish Math Percentile Rank Spanish Math Scaled Score  \
0                          NaN                       NaN   
1                          NaN                       NaN   
2                          NaN                       NaN   
3                          NaN                       NaN   
4                          NaN                       NaN   

   IDEL Instructional Level  Dibels Composite Score Dibels Composite Level  \
0                       NaN                     NaN                    NaN   
1                       NaN                     NaN                    NaN   
2                       NaN                   341.0   Well Below Benchmark   
3                       NaN                   380.0        Below Benchmark   
4                       NaN                     NaN                    NaN   

  Math Benchmark Percent Correct Math Benchmark Performance Level  
0                            NaN                              NaN  
1                            NaN                              NaN  
2                            NaN                              NaN  
3                         0.4872      Needing Significant Support  
4                            NaN                              NaN  

[5 rows x 45 columns]

In [17]:
new_t2_cols_=new_t2.columns.to_list()

In [18]:
new_t2_cols=[]
for col in new_t2_cols_:
    string_col = str(col)
    new_t2_cols.append(string_col)

In [19]:
new_t2_cols

['School',
 'Grade Level',
 'Teacher',
 'Student ID',
 'Last Name',
 'First Name',
 'Gender',
 'Reported Race',
 'Student Is Special Ed?',
 '504.0',
 'English Proficiency',
 'Language',
 'SED from CALPADS',
 'McKV/ Homeless',
 'Vision Scholars',
 'Suspensions through 3/4/22',
 'Attendance through 3/4/22',
 'Writing On Demand',
 'Report Card: English TCRWP',
 'Report Card: English TCRWP level',
 'Report Card: Spanish TCRWP',
 'Report Card: Spanish TCRWP level',
 'Report Card: Op & Alg Thinking',
 'Report Card: Num & Ops in Base Ten',
 'Report Card: Measurement and Data',
 'Report Card: Geometry',
 'Report Card: Math Fluency',
 'STAR Reading District BC Name',
 'STAR Reading State BC Name ',
 'STAR Reading Instructional Reading Level',
 'STAR Reading Scaled Score',
 'STAR Math District BC Name',
 'STAR Math State BC Name',
 'STAR Math Percentile Rank',
 'STAR Math Scaled Score',
 'STAR Math Spanish?',
 'Spanish Math  District BCL',
 'Spanish Math District Benchmark Name',
 'Spanish Math 

In [20]:
i=0
for index, col in enumerate(old_cols):
    if col in new_t2_cols:
        i+=1
        #print(f"col {index} of old data is in the new data")
    else:
        print(f"{col} col isnt in T2 elementary new data")

print(i)


504 col isnt in T2 elementary new data
Suspensions through 10/25 col isnt in T2 elementary new data
Attendance through 10/15 col isnt in T2 elementary new data
Year col isnt in T2 elementary new data
Trimester col isnt in T2 elementary new data
42


In [21]:
i=0
for index, col in enumerate(old_cols):
    if col in new_t2_cols:
        i+=1
        print(f"col {index} of old data is in the new data")

col 0 of old data is in the new data
col 1 of old data is in the new data
col 2 of old data is in the new data
col 3 of old data is in the new data
col 4 of old data is in the new data
col 5 of old data is in the new data
col 7 of old data is in the new data
col 8 of old data is in the new data
col 9 of old data is in the new data
col 10 of old data is in the new data
col 13 of old data is in the new data
col 14 of old data is in the new data
col 15 of old data is in the new data
col 16 of old data is in the new data
col 17 of old data is in the new data
col 18 of old data is in the new data
col 19 of old data is in the new data
col 20 of old data is in the new data
col 21 of old data is in the new data
col 22 of old data is in the new data
col 23 of old data is in the new data
col 24 of old data is in the new data
col 25 of old data is in the new data
col 26 of old data is in the new data
col 27 of old data is in the new data
col 28 of old data is in the new data
col 29 of old data is

### Findings

**1. T1 21-22 (elementary) has all 34/34 of old cols. View output of next cell to delete the ones (3 exactly) that are extra**

**2. T2 21-22 (elementary) has 31/34 of old cols. Col 504.0 and 504 requires renaming (32/34). Suspensions through 10/25 and Attendance through 10/25 cols are misssing (probe further)**

In [22]:
for index, col in enumerate(new_cols):
    if col not in new_t2_cols:
        print(f"{col} col from new elementary data (T1 21-22) must be deleted")

504.0 col from new elementary data (T1 21-22) must be deleted
Suspensions through 10/25 col from new elementary data (T1 21-22) must be deleted
Attendance through 10/15 col from new elementary data (T1 21-22) must be deleted


# 21/22 Data Sheets TK-12 RT Old-New Similarity Check and Incorporation

In [168]:
new_king = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\21_22 Data Sheets TK-12 RT.xlsx", sheet_name="King S1")

In [169]:
new_king.head()

School  Grade Level  Student ID     Last Name  \
0  Martin Luther King Middle School            6     2021427  Abbate-Kahan   
1  Martin Luther King Middle School            6     2021427  Abbate-Kahan   
2  Martin Luther King Middle School            6     2021427  Abbate-Kahan   
3  Martin Luther King Middle School            6     2021427  Abbate-Kahan   
4  Martin Luther King Middle School            6     2021427  Abbate-Kahan   

   First Name Period     Course          Teacher Q1 Grade Grading Task  ...  \
0  Tomas Leon    1+2    ELL 1-2  Taylor, Marcela        4          HOW  ...   
1  Tomas Leon    1+2    ELL 1-2  Taylor, Marcela        4          SBP  ...   
2  Tomas Leon      3     Math 6     Keeley, Ryan        4          HOW  ...   
3  Tomas Leon      3     Math 6     Keeley, Ryan        4          SBP  ...   
4  Tomas Leon      4  Science 6     Keeley, Ryan        3          HOW  ...   

  Suspensions through 10/15 Reported Race Special ED ELA Status Language  \
0                       NaN      Hispanic          N    Not LEP      NaN   
1                       NaN      Hispanic          N    Not LEP      NaN   
2                       NaN      Hispanic          N    Not LEP      NaN   
3                       NaN      Hispanic          N    Not LEP      NaN   
4                       NaN      Hispanic          N    Not LEP      NaN   

   Gender  Ind Study  Socio-Ec Disadv.  504 McKV/Homeless  
0       M        NaN                 N  NaN           NaN  
1       M        NaN                 N  NaN           NaN  
2       M        NaN                 N  NaN           NaN  
3       M        NaN                 N  NaN           NaN  
4       M        NaN                 N  NaN           NaN  

[5 rows x 27 columns]

In [170]:
new_king_cols = new_king.columns.to_list()

In [171]:
new_king_cols

['School',
 'Grade Level',
 'Student ID',
 'Last Name',
 'First Name',
 'Period',
 'Course',
 'Teacher',
 'Q1 Grade',
 'Grading Task',
 'Fall STAR Reading Benchmark Cat.',
 'Winter STAR Reading State Benchmark Cat.',
 'Fall STAR Reading Inst. Reading Level',
 'Fall STAR Math Benchmark Cat.',
 'Winter STAR Math State Benchmark Cat.',
 'Fall STAR Math Percentile Rank',
 'Attendance 8/16 to 10/16',
 'Suspensions through 10/15',
 'Reported Race',
 'Special ED',
 'ELA Status',
 'Language',
 'Gender',
 'Ind Study',
 'Socio-Ec Disadv.',
 504,
 'McKV/Homeless']

In [172]:
old_king = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\rt_fisher_data.xlsx", sheet_name="Q1 Grades")

In [174]:
len(new_king.columns)

27

In [175]:
old_king_cols= old_king.columns.to_list()

In [176]:
old_king_cols
len(old_king_cols)

24

In [177]:
old_king_cols

['School',
 'Grade Level',
 'Student ID',
 'Period',
 'Course',
 'Q1 Grade',
 'Grading Task',
 'Fall STAR Reading Benchmark Cat.',
 'Fall STAR Reading Inst. Reading Level',
 'Fall STAR Math Benchmark Cat.',
 'Fall STAR Math Percentile Rank',
 'Attendance 8/16 to 10/16',
 'Suspensions through 10/15',
 'Reported Race',
 'Special ED',
 'ELA Status',
 'Gender',
 'Ind Study',
 'Socio-Ec Disadv.',
 504,
 'McKV/Homeless',
 'Year',
 'Smester',
 'Quarter']

In [178]:
i=0
for index, col in enumerate(old_king_cols):
    if col in new_king_cols:
        i+=1
        #print(f"col {index} of old data is in the new data")
    else:
        print(f"{col} col not found")

print(i)


Year col not found
Smester col not found
Quarter col not found
21


In [183]:
new_king['Year']='2021-22'
new_king['Smester']=1
new_king['Quarter']=2

In [184]:
new_king

School  Grade Level  Student ID  \
0      Martin Luther King Middle School            6     2021427   
1      Martin Luther King Middle School            6     2021427   
2      Martin Luther King Middle School            6     2021427   
3      Martin Luther King Middle School            6     2021427   
4      Martin Luther King Middle School            6     2021427   
...                                 ...          ...         ...   
11581  Martin Luther King Middle School            8     2018708   
11582  Martin Luther King Middle School            8     2018708   
11583  Martin Luther King Middle School            8     2018708   
11584  Martin Luther King Middle School            8     2018708   
11585  Martin Luther King Middle School            8     2018708   

          Last Name  First Name Period        Course             Teacher  \
0      Abbate-Kahan  Tomas Leon    1+2       ELL 1-2     Taylor, Marcela   
1      Abbate-Kahan  Tomas Leon    1+2       ELL 1-2     Taylor, Marcela   
2      Abbate-Kahan  Tomas Leon      3        Math 6        Keeley, Ryan   
3      Abbate-Kahan  Tomas Leon      3        Math 6        Keeley, Ryan   
4      Abbate-Kahan  Tomas Leon      4     Science 6        Keeley, Ryan   
...             ...         ...    ...           ...                 ...   
11581       Ziegler    Isabella      4  IWE/ Proctor         Holmes, Tom   
11582       Ziegler    Isabella      5     English 8  Klimowicz, Justyna   
11583       Ziegler    Isabella      5     English 8  Klimowicz, Justyna   
11584       Ziegler    Isabella      6     History 8  Klimowicz, Justyna   
11585       Ziegler    Isabella      6     History 8  Klimowicz, Justyna   

      Q1 Grade Grading Task  ... ELA Status Language Gender Ind Study  \
0            4          HOW  ...    Not LEP      NaN      M       NaN   
1            4          SBP  ...    Not LEP      NaN      M       NaN   
2            4          HOW  ...    Not LEP      NaN      M       NaN   
3            4          SBP  ...    Not LEP      NaN      M       NaN   
4            3          HOW  ...    Not LEP      NaN      M       NaN   
...        ...          ...  ...        ...      ...    ...       ...   
11581        4          HOW  ...         EO      NaN      F       NaN   
11582        4          HOW  ...         EO      NaN      F       NaN   
11583        4          SBP  ...         EO      NaN      F       NaN   
11584        4          HOW  ...         EO      NaN      F       NaN   
11585        3          SBP  ...         EO      NaN      F       NaN   

      Socio-Ec Disadv.  504  McKV/Homeless     Year Smester Quarter  
0                    N  NaN            NaN  2021-22       1       2  
1                    N  NaN            NaN  2021-22       1       2  
2                    N  NaN            NaN  2021-22       1       2  
3                    N  NaN            NaN  2021-22       1       2  
4                    N  NaN            NaN  2021-22       1       2  
...                ...  ...            ...      ...     ...     ...  
11581                N  NaN            NaN  2021-22       1       2  
11582                N  NaN            NaN  2021-22       1       2  
11583                N  NaN            NaN  2021-22       1       2  
11584                N  NaN            NaN  2021-22       1       2  
11585                N  NaN            NaN  2021-22       1       2  

[11586 rows x 30 columns]

In [186]:
new_king_incorporated = pd.concat([old_king,new_king],ignore_index=True)

In [194]:
new_king_incorporated.to_excel("new_king_incorporated.xlsx")

**Q2 King S1 successfully incorproated**

In [6]:
import pandas as pd
new_longfellow = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\21_22 Data Sheets TK-12 RT.xlsx", sheet_name="Longfellow S1")

new_longfellow_cols = new_longfellow.columns.to_list()

old_longfellow = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\rt_fisher_data.xlsx", sheet_name="Q1 Grades")

old_longfellow_cols= old_longfellow.columns.to_list()

i=0
for index, col in enumerate(old_longfellow_cols):
    if col in new_longfellow_cols:
        i+=1
        #print(f"col {index} of old data is in the new data")
    else:
        print(f"{col} col not found")

print(i)


Year col not found
Smester col not found
Quarter col not found
27


In [7]:
new_longfellow['Year']='2021-22'
new_longfellow['Smester']=1
new_longfellow['Quarter']=2

In [9]:
new_longfellow

School         Last Name First Name  \
0     Longfellow Magnet Middle School  Acevedo-Schiesel      Lucia   
1     Longfellow Magnet Middle School  Acevedo-Schiesel      Lucia   
2     Longfellow Magnet Middle School  Acevedo-Schiesel      Lucia   
3     Longfellow Magnet Middle School  Acevedo-Schiesel      Lucia   
4     Longfellow Magnet Middle School  Acevedo-Schiesel      Lucia   
...                               ...               ...        ...   
6579  Longfellow Magnet Middle School        Zinabidine     Yasmin   
6580  Longfellow Magnet Middle School        Zinabidine     Yasmin   
6581  Longfellow Magnet Middle School        Zinabidine     Yasmin   
6582  Longfellow Magnet Middle School        Zinabidine     Yasmin   
6583  Longfellow Magnet Middle School        Zinabidine     Yasmin   

      Grade Level  Student ID                Full Name Period      Course  \
0               6     2010214  Acevedo-Schiesel, Lucia      2   Science 6   
1               6     2010214  Acevedo-Schiesel, Lucia      2   Science 6   
2               6     2010214  Acevedo-Schiesel, Lucia      3        PE 6   
3               6     2010214  Acevedo-Schiesel, Lucia      3        PE 6   
4               6     2010214  Acevedo-Schiesel, Lucia      4   History 6   
...           ...         ...                      ...    ...         ...   
6579            8     2008419       Zinabidine, Yasmin      6   English 8   
6580            8     2008419       Zinabidine, Yasmin      6   English 8   
6581            8     2008419       Zinabidine, Yasmin      7   History 8   
6582            8     2008419       Zinabidine, Yasmin      7   History 8   
6583            8     2008419       Zinabidine, Yasmin    Adv  Advisory 8   

              Teacher Q1 Grade  ... Language Gender Ind Study  \
0     Queirolo, Jovel        3  ...      NaN      F       NaN   
1     Queirolo, Jovel        3  ...      NaN      F       NaN   
2         Kelly, Erin        3  ...      NaN      F       NaN   
3         Kelly, Erin        3  ...      NaN      F       NaN   
4     Petrone, Joanna        3  ...      NaN      F       NaN   
...               ...      ...  ...      ...    ...       ...   
6579   Henry, Meaghan        4  ...   Arabic      F       NaN   
6580   Henry, Meaghan        4  ...   Arabic      F       NaN   
6581     Barash, Jill        4  ...   Arabic      F       NaN   
6582     Barash, Jill        4  ...   Arabic      F       NaN   
6583  McMinimy, Molly        4  ...   Arabic      F       NaN   

     Socio-Ec Disadv.  504 McKV/Homeless  Vision Scholars 2021/2022     Year  \
0                   N  NaN           NaN                        NaN  2021-22   
1                   N  NaN           NaN                        NaN  2021-22   
2                   N  NaN           NaN                        NaN  2021-22   
3                   N  NaN           NaN                        NaN  2021-22   
4                   N  NaN           NaN                        NaN  2021-22   
...               ...  ...           ...                        ...      ...   
6579                Y  NaN           NaN                        NaN  2021-22   
6580                Y  NaN           NaN                        NaN  2021-22   
6581                Y  NaN           NaN                        NaN  2021-22   
6582                Y  NaN           NaN                        NaN  2021-22   
6583                Y  NaN           NaN                        NaN  2021-22   

     Smester  Quarter  
0          1        2  
1          1        2  
2          1        2  
3          1        2  
4          1        2  
...      ...      ...  
6579       1        2  
6580       1        2  
6581       1        2  
6582       1        2  
6583       1        2  

[6584 rows x 33 columns]

In [13]:
new_longfellow_incorporated = pd.concat([old_longfellow,new_longfellow],ignore_index=True)

In [16]:
new_longfellow_incorporated

School  Grade Level  Student ID Period  \
0                 Berkeley High School            9     2006000      1   
1                 Berkeley High School            9     2006000      2   
2                 Berkeley High School            9     2006000      3   
3                 Berkeley High School            9     2006000      4   
4                 Berkeley High School            9     2006000      5   
...                                ...          ...         ...    ...   
63852  Longfellow Magnet Middle School            8     2008419      6   
63853  Longfellow Magnet Middle School            8     2008419      6   
63854  Longfellow Magnet Middle School            8     2008419      7   
63855  Longfellow Magnet Middle School            8     2008419      7   
63856  Longfellow Magnet Middle School            8     2008419    Adv   

                Course Q1 Grade   Grading Task  \
0        Physics 1 (P)       B-  Quarter Grade   
1              INE-CLC        A  Quarter Grade   
2      FrshSemHist (P)       B-  Quarter Grade   
3            Spanish I       B-  Quarter Grade   
4        English 1 (P)       D-  Quarter Grade   
...                ...      ...            ...   
63852        English 8        4            HOW   
63853        English 8        4            SBP   
63854        History 8        4            HOW   
63855        History 8        4            SBP   
63856       Advisory 8        4            HOW   

      Fall STAR Reading Benchmark Cat. Fall STAR Reading Inst. Reading Level  \
0                                  NaN                                   NaN   
1                                  NaN                                   NaN   
2                                  NaN                                   NaN   
3                                  NaN                                   NaN   
4                                  NaN                                   NaN   
...                                ...                                   ...   
63852               At/Above Benchmark                                     8   
63853               At/Above Benchmark                                     8   
63854               At/Above Benchmark                                     8   
63855               At/Above Benchmark                                     8   
63856               At/Above Benchmark                                     8   

      Fall STAR Math Benchmark Cat.  ... Quarter   Last Name  First Name  \
0                               NaN  ...       1         NaN         NaN   
1                               NaN  ...       1         NaN         NaN   
2                               NaN  ...       1         NaN         NaN   
3                               NaN  ...       1         NaN         NaN   
4                               NaN  ...       1         NaN         NaN   
...                             ...  ...     ...         ...         ...   
63852                  Intervention  ...       2  Zinabidine      Yasmin   
63853                  Intervention  ...       2  Zinabidine      Yasmin   
63854                  Intervention  ...       2  Zinabidine      Yasmin   
63855                  Intervention  ...       2  Zinabidine      Yasmin   
63856                  Intervention  ...       2  Zinabidine      Yasmin   

               Teacher Winter STAR Reading State Benchmark Cat.  \
0                  NaN                                      NaN   
1                  NaN                                      NaN   
2                  NaN                                      NaN   
3                  NaN                                      NaN   
4                  NaN                                      NaN   
...                ...                                      ...   
63852   Henry, Meaghan                                 On Watch   
63853   Henry, Meaghan                                 On Watch   
63854     Barash, Jill                                 On Watch  

In [17]:
new_longfellow_incorporated.to_excel("new_longfellow_incorporated.xlsx")

**Q2 Longfellow S1 successfully incorproated**

In [27]:
new_williard = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\21_22 Data Sheets TK-12 RT.xlsx", sheet_name="Willard S1")

new_williard_cols = new_williard.columns.to_list()

old_williard = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\rt_fisher_data.xlsx", sheet_name="Q1 Grades")

old_williard_cols= old_williard.columns.to_list()

i=0
for index, col in enumerate(old_williard_cols):
    if col in new_williard_cols:
        i+=1
        #print(f"col {index} of old data is in the new data")
    else:
        print(f"{col} col not found")

print(i)


Year col not found
Smester col not found
Quarter col not found
Full Name col not found
Growth Category ELA col not found
Vision Scholars 2021/2022 col not found
27


In [28]:
new_williard['Year']='2021-22'
new_williard['Smester']=1
new_williard['Quarter']=2

In [29]:
new_williard

School  Grade Level  Student ID         Last Name  \
0     Willard Middle School            6     2010945     Abdu-Mohammed   
1     Willard Middle School            6     2010945     Abdu-Mohammed   
2     Willard Middle School            6     2010945     Abdu-Mohammed   
3     Willard Middle School            6     2010945     Abdu-Mohammed   
4     Willard Middle School            6     2010945     Abdu-Mohammed   
...                     ...          ...         ...               ...   
7590  Willard Middle School            8     2007553  Zubeldia-Lippman   
7591  Willard Middle School            8     2007553  Zubeldia-Lippman   
7592  Willard Middle School            8     2007553  Zubeldia-Lippman   
7593  Willard Middle School            8     2007553  Zubeldia-Lippman   
7594  Willard Middle School            8     2007553  Zubeldia-Lippman   

     First Name    Period           Course            Teacher Q1 Grade  \
0       Mohamed         1           Math 6  MacCarthy, Robert        3   
1       Mohamed         1           Math 6  MacCarthy, Robert        2   
2       Mohamed         2        Science 6  MacCarthy, Robert        4   
3       Mohamed         2        Science 6  MacCarthy, Robert        4   
4       Mohamed         3        Reading 6     Bonsall, Patty        2   
...         ...       ...              ...                ...      ...   
7590      Diego         4           Math 8    Nguyen, Kimhong        3   
7591      Diego         5  Growing Leaders    Mc Clure, Ellen        4   
7592      Diego         6             PE 8         Fike, John        4   
7593      Diego         6             PE 8         Fike, John      NaN   
7594      Diego  Advisory         Advisory         Hom, Ivana        4   

     Grading Task  ... ELA Status  Language Gender Ind Study Socio-Ec Disadv.  \
0             HOW  ...        LEP  Tigrinya      M       NaN                Y   
1             SBP  ...        LEP  Tigrinya      M       NaN                Y   
2             HOW  ...        LEP  Tigrinya      M       NaN                Y   
3             SBP  ...        LEP  Tigrinya      M       NaN                Y   
4             HOW  ...        LEP  Tigrinya      M       NaN                Y   
...           ...  ...        ...       ...    ...       ...              ...   
7590          SBP  ...         EO       NaN      M       NaN                N   
7591          HOW  ...         EO       NaN      M       NaN                N   
7592          HOW  ...         EO       NaN      M       NaN                N   
7593          SBP  ...         EO       NaN      M       NaN                N   
7594          HOW  ...         EO       NaN      M       NaN                N   

      504  McKV/Homeless     Year Smester Quarter  
0     NaN            NaN  2021-22       1       2  
1     NaN            NaN  2021-22       1       2  
2     NaN            NaN  2021-22       1       2  
3     NaN            NaN  2021-22       1       2  
4     NaN            NaN  2021-22       1       2  
...   ...            ...      ...     ...     ...  
7590    Y            NaN  2021-22       1       2  
7591    Y            NaN  2021-22       1       2  
7592    Y            NaN  2021-22       1       2  
7593    Y            NaN  2021-22       1       2  
7594    Y            NaN  2021-22       1       2  

[7595 rows x 30 columns]

In [30]:
new_williard_incorporated = pd.concat([old_williard,new_williard],ignore_index=True)

In [31]:
new_williard_incorporated

School  Grade Level  Student ID    Period  \
0       Berkeley High School            9     2006000         1   
1       Berkeley High School            9     2006000         2   
2       Berkeley High School            9     2006000         3   
3       Berkeley High School            9     2006000         4   
4       Berkeley High School            9     2006000         5   
...                      ...          ...         ...       ...   
71447  Willard Middle School            8     2007553         4   
71448  Willard Middle School            8     2007553         5   
71449  Willard Middle School            8     2007553         6   
71450  Willard Middle School            8     2007553         6   
71451  Willard Middle School            8     2007553  Advisory   

                Course Q1 Grade   Grading Task  \
0        Physics 1 (P)       B-  Quarter Grade   
1              INE-CLC        A  Quarter Grade   
2      FrshSemHist (P)       B-  Quarter Grade   
3            Spanish I       B-  Quarter Grade   
4        English 1 (P)       D-  Quarter Grade   
...                ...      ...            ...   
71447           Math 8        3            SBP   
71448  Growing Leaders        4            HOW   
71449             PE 8        4            HOW   
71450             PE 8      NaN            SBP   
71451         Advisory        4            HOW   

      Fall STAR Reading Benchmark Cat. Fall STAR Reading Inst. Reading Level  \
0                                  NaN                                   NaN   
1                                  NaN                                   NaN   
2                                  NaN                                   NaN   
3                                  NaN                                   NaN   
4                                  NaN                                   NaN   
...                                ...                                   ...   
71447                         On Watch                                   7.1   
71448                         On Watch                                   7.1   
71449                         On Watch                                   7.1   
71450                         On Watch                                   7.1   
71451                         On Watch                                   7.1   

      Fall STAR Math Benchmark Cat.  ... Quarter         Last Name  \
0                               NaN  ...       1               NaN   
1                               NaN  ...       1               NaN   
2                               NaN  ...       1               NaN   
3                               NaN  ...       1               NaN   
4                               NaN  ...       1               NaN   
...                             ...  ...     ...               ...   
71447            At/Above Benchmark  ...       2  Zubeldia-Lippman   
71448            At/Above Benchmark  ...       2  Zubeldia-Lippman   
71449            At/Above Benchmark  ...       2  Zubeldia-Lippman   
71450            At/Above Benchmark  ...       2  Zubeldia-Lippman   
71451            At/Above Benchmark  ...       2  Zubeldia-Lippman   

       First Name          Teacher Winter STAR Reading State Benchmark Cat.  \
0             NaN              NaN                                      NaN   
1             NaN              NaN                                      NaN   
2             NaN              NaN                                      NaN   
3             NaN              NaN                                      NaN   
4             NaN              NaN                                      NaN   
...           ...              ...                                      ...   
71447       Diego  Nguyen, Kimhong                             Intervention   
71448       Diego  Mc Clure, Ellen                             Intervention   
71449       Diego       Fike, John                             Intervention   
71450       Diego       

In [32]:
new_williard_incorporated.to_excel("new_williard_incorporated.xlsx")

**Q2 Willard S1 successfully incorporated**

In [35]:
new_bhs = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\21_22 Data Sheets TK-12 RT.xlsx", sheet_name="BHSBTA S1")

new_bhs_cols = new_bhs.columns.to_list()

old_bhs = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\rt_fisher_data.xlsx", sheet_name="Q1 Grades")

old_bhs_cols= old_bhs.columns.to_list()

i=0
for index, col in enumerate(old_bhs_cols):
    if col in new_bhs_cols:
        i+=1
        #print(f"col {index} of old data is in the new data")
    else:
        print(f"{col} col not found")

print(i)


Grading Task col not found
Fall STAR Reading Benchmark Cat. col not found
Fall STAR Reading Inst. Reading Level col not found
Fall STAR Math Benchmark Cat. col not found
Fall STAR Math Percentile Rank col not found
Year col not found
Smester col not found
Quarter col not found
Winter STAR Reading State Benchmark Cat. col not found
Winter STAR Math State Benchmark Cat. col not found
Language col not found
Full Name col not found
Growth Category ELA col not found
Vision Scholars 2021/2022 col not found
19


In [36]:
new_bhs['Year']='2021-22'
new_bhs['Smester']=1
new_bhs['Quarter']=2

In [37]:
new_bhs

School     SLC  Grade Level  Student ID  \
0             Berkeley High School  Hive 1            9     2006000   
1             Berkeley High School  Hive 1            9     2006000   
2             Berkeley High School  Hive 1            9     2006000   
3             Berkeley High School  Hive 1            9     2006000   
4             Berkeley High School  Hive 1            9     2006000   
...                            ...     ...          ...         ...   
19997  Berkeley Technology Academy     NaN           12     2000815   
19998  Berkeley Technology Academy     NaN           12     2000815   
19999  Berkeley Technology Academy     NaN           12     2000815   
20000  Berkeley Technology Academy     NaN           12     2000815   
20001  Berkeley Technology Academy     NaN           12     2000815   

           Last Name First Name Period                Course  \
0      Abdu-Mohammed     Zemzem      1         Physics 1 (P)   
1      Abdu-Mohammed     Zemzem      2               INE-CLC   
2      Abdu-Mohammed     Zemzem      3       FrshSemHist (P)   
3      Abdu-Mohammed     Zemzem      4             Spanish I   
4      Abdu-Mohammed     Zemzem      5         English 1 (P)   
...              ...        ...    ...                   ...   
19997       Williams   Demarcus      2        BTch-Genre Lit   
19998       Williams   Demarcus      3           BTch-Math 3   
19999       Williams   Demarcus      1        BTch-Economics   
20000       Williams   Demarcus      2  BTch-World History B   
20001       Williams   Demarcus      3        BTch-Genre Lit   

                 Teacher Q1 Grade  ...       Special ED  ELA Status Gender  \
0        Altawil, Adrian        C  ...                Y  Exited LEP      F   
1           Austin, Tara        A  ...                Y  Exited LEP      F   
2      Minassian, Hasmig        C  ...                Y  Exited LEP      F   
3          Kelly, Alison        B  ...                Y  Exited LEP      F   
4        Omwamba, Joseph        C  ...                Y  Exited LEP      F   
...                  ...      ...  ...              ...         ...    ...   
19997    Randle, Sherene        A  ...  BlackAfricanAme          EO      M   
19998    Lamar-El, Ramal       B+  ...  BlackAfricanAme          EO      M   
19999    Sclafani, Jesse       A-  ...  BlackAfricanAme          EO      M   
20000    Lamar-El, Ramal       B+  ...  BlackAfricanAme          EO      M   
20001    Randle, Sherene        A  ...  BlackAfricanAme          EO      M   

      Ind Study Socio-Ec Disadv.  504 McKV/Homeless     Year Smester Quarter  
0           NaN                Y  NaN             F  2021-22       1       2  
1           NaN                Y  NaN             F  2021-22       1       2  
2           NaN                Y  NaN             F  2021-22       1       2  
3           NaN                Y  NaN             F  2021-22       1       2  
4           NaN                Y  NaN             F  2021-22       1       2  
...         ...              ...  ...           ...      ...     ...     ...  
19997       NaN                Y  NaN             F  2021-22       1       2  
19998       NaN                Y  NaN             F  2021-22       1       2  
19999       NaN                Y  NaN             F  2021-22       1       2  
20000       NaN                Y  NaN             F  2021-22       1       2  
20001       NaN                Y  NaN             F  2021-22       1       2  

[20002 rows x 23 columns]

In [38]:
new_bhs_incorporated = pd.concat([old_bhs,new_bhs],ignore_index=True)

In [39]:
new_bhs_incorporated

School  Grade Level  Student ID Period  \
0             Berkeley High School            9     2006000      1   
1             Berkeley High School            9     2006000      2   
2             Berkeley High School            9     2006000      3   
3             Berkeley High School            9     2006000      4   
4             Berkeley High School            9     2006000      5   
...                            ...          ...         ...    ...   
91449  Berkeley Technology Academy           12     2000815      2   
91450  Berkeley Technology Academy           12     2000815      3   
91451  Berkeley Technology Academy           12     2000815      1   
91452  Berkeley Technology Academy           12     2000815      2   
91453  Berkeley Technology Academy           12     2000815      3   

                     Course Q1 Grade   Grading Task  \
0             Physics 1 (P)       B-  Quarter Grade   
1                   INE-CLC        A  Quarter Grade   
2           FrshSemHist (P)       B-  Quarter Grade   
3                 Spanish I       B-  Quarter Grade   
4             English 1 (P)       D-  Quarter Grade   
...                     ...      ...            ...   
91449        BTch-Genre Lit        A            NaN   
91450           BTch-Math 3       B+            NaN   
91451        BTch-Economics       A-            NaN   
91452  BTch-World History B       B+            NaN   
91453        BTch-Genre Lit        A            NaN   

      Fall STAR Reading Benchmark Cat. Fall STAR Reading Inst. Reading Level  \
0                                  NaN                                   NaN   
1                                  NaN                                   NaN   
2                                  NaN                                   NaN   
3                                  NaN                                   NaN   
4                                  NaN                                   NaN   
...                                ...                                   ...   
91449                              NaN                                   NaN   
91450                              NaN                                   NaN   
91451                              NaN                                   NaN   
91452                              NaN                                   NaN   
91453                              NaN                                   NaN   

      Fall STAR Math Benchmark Cat.  ... Last Name First Name  \
0                               NaN  ...       NaN        NaN   
1                               NaN  ...       NaN        NaN   
2                               NaN  ...       NaN        NaN   
3                               NaN  ...       NaN        NaN   
4                               NaN  ...       NaN        NaN   
...                             ...  ...       ...        ...   
91449                           NaN  ...  Williams   Demarcus   
91450                           NaN  ...  Williams   Demarcus   
91451                           NaN  ...  Williams   Demarcus   
91452                           NaN  ...  Williams   Demarcus   
91453                           NaN  ...  Williams   Demarcus   

               Teacher Winter STAR Reading State Benchmark Cat.  \
0                  NaN                                      NaN   
1                  NaN                                      NaN   
2                  NaN                                      NaN   
3                  NaN                                      NaN   
4                  NaN                                      NaN   
...                ...                                      ...   
91449  Randle, Sherene                                      NaN   
91450  Lamar-El, Ramal                                      NaN   
91451  Sclafani, Jesse                                      NaN   
91452  Lamar-El, Ramal                                      NaN   
91453  Randle, Sherene                         

In [40]:
new_bhs_incorporated.to_excel("new_bhs_incorporated.xlsx")

**Q2 BHS successfully incorporated**

# Quarter 3 Middle and High Incorporation

In [56]:
q3_longfellow = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\Quarter 3 Middle and High RT.xlsx", sheet_name="Longfellow")

q3_longfellow_cols = q3_longfellow.columns.to_list()

old_longfellow = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\rt_fisher_data.xlsx", sheet_name="Q1 Grades")

old_longfellow_cols= old_longfellow.columns.to_list()

i=0
for index, col in enumerate(old_longfellow_cols):
    if col in q3_longfellow_cols:
        i+=1
        #print(f"col {index} of old data is in the new data")
    else:
        print(f"{col} col not found")

print(i)


Unnamed: 0 col not found
Period col not found
Grading Task col not found
Fall STAR Reading Benchmark Cat. col not found
Fall STAR Reading Inst. Reading Level col not found
Fall STAR Math Benchmark Cat. col not found
Fall STAR Math Percentile Rank col not found
Ind Study col not found
Socio-Ec Disadv. col not found
504 col not found
McKV/Homeless col not found
Year col not found
Smester col not found
Quarter col not found
Last Name col not found
First Name col not found
Winter STAR Reading State Benchmark Cat. col not found
Winter STAR Math State Benchmark Cat. col not found
Full Name col not found
Growth Category ELA col not found
Vision Scholars 2021/2022 col not found
SLC col not found
27


In [50]:
q3_longfellow['Year']='2021-22'
q3_longfellow['Smester']=2
q3_longfellow['Quarter']=3

In [51]:
q3_longfellow

School  Grade Level               Last  \
0     Longfellow Magnet Middle School            6  Barraza Navarrete   
1     Longfellow Magnet Middle School            6  Barraza Navarrete   
2     Longfellow Magnet Middle School            6  Barraza Navarrete   
3     Longfellow Magnet Middle School            6  Barraza Navarrete   
4     Longfellow Magnet Middle School            6  Barraza Navarrete   
...                               ...          ...                ...   
6703  Longfellow Magnet Middle School            8             DePina   
6704  Longfellow Magnet Middle School            8             DePina   
6705  Longfellow Magnet Middle School            8             DePina   
6706  Longfellow Magnet Middle School            8             DePina   
6707  Longfellow Magnet Middle School            8             DePina   

        First  Student ID  In-School Suspension  Suspensions through 10/15  \
0     Jocelyn     2008941                   NaN                        NaN   
1     Jocelyn     2008941                   NaN                        NaN   
2     Jocelyn     2008941                   NaN                        NaN   
3     Jocelyn     2008941                   NaN                        NaN   
4     Jocelyn     2008941                   NaN                        NaN   
...       ...         ...                   ...                        ...   
6703    Avery     2021384                   NaN                        NaN   
6704    Avery     2021384                   NaN                        NaN   
6705    Avery     2021384                   NaN                        NaN   
6706    Avery     2021384                   NaN                        NaN   
6707    Avery     2021384                   NaN                        NaN   

      Attendance 8/16 to 10/16             Course           Teacher  ...  \
0                       0.9487  Introductory Band  Andreatta, Jonah  ...   
1                       0.9487  Introductory Band  Andreatta, Jonah  ...   
2                       0.9487               PE 6   McEvoy, Michael  ...   
3                       0.9487               PE 6   McEvoy, Michael  ...   
4                       0.9487      TWI History 6   Patterson, Mary  ...   
...                        ...                ...               ...  ...   
6703                    0.7586  Intro to Dance/PE       Kelly, Erin  ...   
6704                    0.7586  Intro to Dance/PE       Kelly, Erin  ...   
6705                    0.7586             Design       Tran, Jimmy  ...   
6706                    0.7586             Design       Tran, Jimmy  ...   
6707                    0.7586         Advisory 8      Barash, Jill  ...   

     PROGRESS Score Gender    Reported Race Special ED  ELA Status  \
0               4.0      F         Hispanic          N  Exited LEP   
1               4.0      F         Hispanic          N  Exited LEP   
2               3.0      F         Hispanic          N  Exited LEP   
3               3.0      F         Hispanic          N  Exited LEP   
4               3.0      F         Hispanic          N  Exited LEP   
...             ...    ...              ...        ...         ...   
6703            4.0      M  AmerIndianAlask          N          EO   
6704            4.0      M  AmerIndianAlask          N          EO   
6705            2.0      M  AmerIndianAlask          N          EO   
6706            4.0      M  AmerIndianAlask          N          EO   
6707            4.0      M  AmerIndianAlask          N          EO   

      Active Today  Language     Year  Smester  Quarter  
0                1       NaN  2021-22        2        3  
1                1       1.0  2021-22        2        3  
2                1       1.0  2021-22        2        3  
3                1       1.0  2021-22        2        3  
4                1       1.0  2021-22        2        3  
...            ...       ...      ...      ...      ...  
6703             1       0.0  2021-22        2        3  

In [52]:
q3_longfellow_incorporated = pd.concat([old_longfellow,q3_longfellow],ignore_index=True)

In [53]:
q3_longfellow_incorporated

School  Grade Level  Student ID Period  \
0                 Berkeley High School            9     2006000      1   
1                 Berkeley High School            9     2006000      2   
2                 Berkeley High School            9     2006000      3   
3                 Berkeley High School            9     2006000      4   
4                 Berkeley High School            9     2006000      5   
...                                ...          ...         ...    ...   
98157  Longfellow Magnet Middle School            8     2021384    NaN   
98158  Longfellow Magnet Middle School            8     2021384    NaN   
98159  Longfellow Magnet Middle School            8     2021384    NaN   
98160  Longfellow Magnet Middle School            8     2021384    NaN   
98161  Longfellow Magnet Middle School            8     2021384    NaN   

                  Course Q1 Grade   Grading Task  \
0          Physics 1 (P)       B-  Quarter Grade   
1                INE-CLC        A  Quarter Grade   
2        FrshSemHist (P)       B-  Quarter Grade   
3              Spanish I       B-  Quarter Grade   
4          English 1 (P)       D-  Quarter Grade   
...                  ...      ...            ...   
98157  Intro to Dance/PE        4            NaN   
98158  Intro to Dance/PE        4            NaN   
98159             Design      NaN            NaN   
98160             Design        4            NaN   
98161         Advisory 8        4            NaN   

      Fall STAR Reading Benchmark Cat. Fall STAR Reading Inst. Reading Level  \
0                                  NaN                                   NaN   
1                                  NaN                                   NaN   
2                                  NaN                                   NaN   
3                                  NaN                                   NaN   
4                                  NaN                                   NaN   
...                                ...                                   ...   
98157                              NaN                                   NaN   
98158                              NaN                                   NaN   
98159                              NaN                                   NaN   
98160                              NaN                                   NaN   
98161                              NaN                                   NaN   

      Fall STAR Math Benchmark Cat.  ... Task Term Name  Course Num  \
0                               NaN  ...  NaN       NaN         NaN   
1                               NaN  ...  NaN       NaN         NaN   
2                               NaN  ...  NaN       NaN         NaN   
3                               NaN  ...  NaN       NaN         NaN   
4                               NaN  ...  NaN       NaN         NaN   
...                             ...  ...  ...       ...         ...   
98157                           NaN  ...  HOW        Q3        7565   
98158                           NaN  ...  SBP        Q3        7565   
98159                           NaN  ...  SBP        Q3        7453   
98160                           NaN  ...  HOW        Q3        7453   
98161                           NaN  ...  HOW        Q3        7702   

      Section Num Term ID Credit Credit Type Course ID PROGRESS Score  \
0             NaN     NaN    NaN         NaN       NaN            NaN   
1             NaN     NaN    NaN         NaN       NaN            NaN   
2             NaN     NaN    NaN         NaN       NaN            NaN   
3             NaN     NaN    NaN         NaN       NaN            NaN   
4             NaN     NaN    NaN         NaN       NaN            NaN   
...           ...     ...    ...         ...       ...            ...   
98157         2.0   650.0    NaN         NaN   55018.0            4.0   
98158         2.0   650.0    NaN         NaN   55018.0            4.0   
98159         1.0   650.0    NaN         NaN   

In [55]:
q3_longfellow_incorporated.to_excel("q3_longfellow_incorporated.xlsx")

**Q3 Longfellow successfully incorporated**

In [59]:
q3_king = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\Quarter 3 Middle and High RT.xlsx", sheet_name="King")

q3_king_cols = q3_king.columns.to_list()

old_king = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\rt_fisher_data.xlsx", sheet_name="Q1 Grades")

old_king_cols= old_king.columns.to_list()

i=0
for index, col in enumerate(old_king_cols):
    if col in q3_king_cols:
        i+=1
        #print(f"col {index} of old data is in the new data")
    else:
        print(f"{col} col not found")

print(i)


Period col not found
Grading Task col not found
Fall STAR Reading Benchmark Cat. col not found
Fall STAR Reading Inst. Reading Level col not found
Fall STAR Math Benchmark Cat. col not found
Fall STAR Math Percentile Rank col not found
Ind Study col not found
Socio-Ec Disadv. col not found
504 col not found
McKV/Homeless col not found
Year col not found
Smester col not found
Quarter col not found
Last Name col not found
First Name col not found
Winter STAR Reading State Benchmark Cat. col not found
Winter STAR Math State Benchmark Cat. col not found
Full Name col not found
Growth Category ELA col not found
Vision Scholars 2021/2022 col not found
SLC col not found
27


In [60]:
q3_king['Year']='2021-22'
q3_king['Smester']=2
q3_king['Quarter']=3

In [61]:
q3_king

School  Grade Level                   Last  \
0      Martin Luther King Middle School            6                Thorton   
1      Martin Luther King Middle School            6                Thorton   
2      Martin Luther King Middle School            6                Thorton   
3      Martin Luther King Middle School            6                Thorton   
4      Martin Luther King Middle School            6                Thorton   
...                                 ...          ...                    ...   
11635  Martin Luther King Middle School            8  Valdeavellano Fuentes   
11636  Martin Luther King Middle School            8  Valdeavellano Fuentes   
11637  Martin Luther King Middle School            8  Valdeavellano Fuentes   
11638  Martin Luther King Middle School            8  Valdeavellano Fuentes   
11639  Martin Luther King Middle School            8  Valdeavellano Fuentes   

        First  Student ID  In-School Suspension  Suspensions through 10/15  \
0       Amira     2007801                   NaN                        1.0   
1       Amira     2007801                   NaN                        1.0   
2       Amira     2007801                   NaN                        1.0   
3       Amira     2007801                   NaN                        1.0   
4       Amira     2007801                   NaN                        1.0   
...       ...         ...                   ...                        ...   
11635  Ismael     2022054                   NaN                        NaN   
11636  Ismael     2022054                   NaN                        NaN   
11637  Ismael     2022054                   NaN                        NaN   
11638  Ismael     2022054                   NaN                        NaN   
11639  Ismael     2022054                   NaN                        NaN   

       Attendance 8/16 to 10/16         Course              Teacher  ...  \
0                        0.8790  ISP Science 6      Felarca, Yvette  ...   
1                        0.8790  ISP Science 6      Felarca, Yvette  ...   
2                        0.8790  ISP English 6      Felarca, Yvette  ...   
3                        0.8790  ISP English 6      Felarca, Yvette  ...   
4                        0.8790  ISP History 6      Felarca, Yvette  ...   
...                         ...            ...                  ...  ...   
11635                    0.9688      Science 8  Schoenfeldt, Gloria  ...   
11636                    0.9688      Science 8  Schoenfeldt, Gloria  ...   
11637                    0.9688      English 8          Hotter, Mya  ...   
11638                    0.9688           PE 8        Martin, Frank  ...   
11639                    0.9688           PE 8        Martin, Frank  ...   

      PROGRESS Score Gender    Reported Race Special ED ELA Status  \
0                3.0      F  BlackAfricanAme          N         EO   
1                3.0      F  BlackAfricanAme          N         EO   
2                3.0      F  BlackAfricanAme          N         EO   
3                3.0      F  BlackAfricanAme          N         EO   
4                3.0      F  BlackAfricanAme          N         EO   
...              ...    ...              ...        ...        ...   
11635            NaN      M         Hispanic          N    Pending   
11636            NaN      M         Hispanic          N    Pending   
11637            NaN      M         Hispanic          N    Pending   
11638            NaN      M         Hispanic          N    Pending   
11639            NaN      M         Hispanic          N    Pending   

       Active Today  Language     Year  Smester  Quarter  
0                 1         0  2021-22        2        3  
1                 1         0  2021-22        2        3  
2                 1         0  2021-22        2        3  
3                 1         0  2021-22        2        3  
4                 1         0  2021-22        2        3  
...             ...       ...      ... 

In [62]:
q3_king_incorporated = pd.concat([old_king,q3_king],ignore_index=True)

In [63]:
q3_king_incorporated

School  Grade Level  Student ID Period  \
0                   Berkeley High School            9     2006000      1   
1                   Berkeley High School            9     2006000      2   
2                   Berkeley High School            9     2006000      3   
3                   Berkeley High School            9     2006000      4   
4                   Berkeley High School            9     2006000      5   
...                                  ...          ...         ...    ...   
109797  Martin Luther King Middle School            8     2022054    NaN   
109798  Martin Luther King Middle School            8     2022054    NaN   
109799  Martin Luther King Middle School            8     2022054    NaN   
109800  Martin Luther King Middle School            8     2022054    NaN   
109801  Martin Luther King Middle School            8     2022054    NaN   

                 Course Q1 Grade   Grading Task  \
0         Physics 1 (P)       B-  Quarter Grade   
1               INE-CLC        A  Quarter Grade   
2       FrshSemHist (P)       B-  Quarter Grade   
3             Spanish I       B-  Quarter Grade   
4         English 1 (P)       D-  Quarter Grade   
...                 ...      ...            ...   
109797        Science 8       NG            NaN   
109798        Science 8       NG            NaN   
109799        English 8      NaN            NaN   
109800             PE 8      NaN            NaN   
109801             PE 8      NaN            NaN   

       Fall STAR Reading Benchmark Cat. Fall STAR Reading Inst. Reading Level  \
0                                   NaN                                   NaN   
1                                   NaN                                   NaN   
2                                   NaN                                   NaN   
3                                   NaN                                   NaN   
4                                   NaN                                   NaN   
...                                 ...                                   ...   
109797                              NaN                                   NaN   
109798                              NaN                                   NaN   
109799                              NaN                                   NaN   
109800                              NaN                                   NaN   
109801                              NaN                                   NaN   

       Fall STAR Math Benchmark Cat.  ... Task Term Name  Course Num  \
0                                NaN  ...  NaN       NaN         NaN   
1                                NaN  ...  NaN       NaN         NaN   
2                                NaN  ...  NaN       NaN         NaN   
3                                NaN  ...  NaN       NaN         NaN   
4                                NaN  ...  NaN       NaN         NaN   
...                              ...  ...  ...       ...         ...   
109797                           NaN  ...  HOW        Q3        7450   
109798                           NaN  ...  SBP        Q3        7450   
109799                           NaN  ...  HOW        Q3        7150   
109800                           NaN  ...  HOW        Q3        7550   
109801                           NaN  ...  SBP        Q3        7550   

       Section Num Term ID Credit Credit Type Course ID PROGRESS Score  \
0              NaN     NaN    NaN         NaN       NaN            NaN   
1              NaN     NaN    NaN         NaN       NaN            NaN   
2              NaN     NaN    NaN         NaN       NaN            NaN   
3              NaN     NaN    NaN         NaN       NaN            NaN   
4              NaN     NaN    NaN         NaN       NaN            NaN   
...            ...     ...    ...         ...       ...            ...   
109797         8.0   614.0    NaN         NaN   55193.0            NaN   
109798         8.0   614.0    NaN         NaN   55193.0            NaN   
1097

In [64]:
q3_king_incorporated.to_excel("q3_king_incorporated.xlsx")

**Q3 King successfully incorporated**

In [66]:
q3_willard = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\Quarter 3 Middle and High RT.xlsx", sheet_name="Willard")

q3_willard_cols = q3_willard.columns.to_list()

old_willard = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\rt_fisher_data.xlsx", sheet_name="Q1 Grades")

old_willard_cols= old_willard.columns.to_list()

i=0
for index, col in enumerate(old_willard_cols):
    if col in q3_willard_cols:
        i+=1
        #print(f"col {index} of old data is in the new data")
    else:
        print(f"{col} col not found")

print(i)


Period col not found
Grading Task col not found
Fall STAR Reading Benchmark Cat. col not found
Fall STAR Reading Inst. Reading Level col not found
Fall STAR Math Benchmark Cat. col not found
Fall STAR Math Percentile Rank col not found
Ind Study col not found
Socio-Ec Disadv. col not found
504 col not found
McKV/Homeless col not found
Year col not found
Smester col not found
Quarter col not found
Last Name col not found
First Name col not found
Winter STAR Reading State Benchmark Cat. col not found
Winter STAR Math State Benchmark Cat. col not found
Full Name col not found
Growth Category ELA col not found
Vision Scholars 2021/2022 col not found
SLC col not found
27


In [67]:
q3_willard['Year']='2021-22'
q3_willard['Smester']=2
q3_willard['Quarter']=3

In [68]:
q3_willard

School  Grade Level            Last     First  \
0     Willard Middle School            6  Haefele-Thomas     Jalen   
1     Willard Middle School            6  Haefele-Thomas     Jalen   
2     Willard Middle School            6  Haefele-Thomas     Jalen   
3     Willard Middle School            6  Haefele-Thomas     Jalen   
4     Willard Middle School            6  Haefele-Thomas     Jalen   
...                     ...          ...             ...       ...   
7737  Willard Middle School            8           Gomez   Allison   
7738  Willard Middle School            8           Gomez   Allison   
7739  Willard Middle School            8         Stephen  Destiney   
7740  Willard Middle School            8         Stephen  Destiney   
7741  Willard Middle School            8         Stephen  Destiney   

      Student ID  In-School Suspension  Suspensions through 10/15  \
0        2007210                   NaN                        NaN   
1        2007210                   NaN                        NaN   
2        2007210                   NaN                        NaN   
3        2007210                   NaN                        NaN   
4        2007210                   NaN                        NaN   
...          ...                   ...                        ...   
7737     2021187                   NaN                        NaN   
7738     2021187                   NaN                        NaN   
7739     2021326                   NaN                        NaN   
7740     2021326                   NaN                        NaN   
7741     2021326                   NaN                        NaN   

      Attendance 8/16 to 10/16          Course          Teacher  ...  \
0                       0.7885          Math 6   Arthur, Sharon  ...   
1                       0.7885          Math 6   Arthur, Sharon  ...   
2                       0.7885       Science 6   Arthur, Sharon  ...   
3                       0.7885       Science 6   Arthur, Sharon  ...   
4                       0.7885            PE 6       Fike, John  ...   
...                        ...             ...              ...  ...   
7737                    0.9872        Advisory  Nguyen, Kimhong  ...   
7738                    0.9872        Advisory  Nguyen, Kimhong  ...   
7739                    0.7596          Math 8  Nguyen, Kimhong  ...   
7740                    0.7596          Math 8  Nguyen, Kimhong  ...   
7741                    0.7596  Math 8 Support  Nguyen, Kimhong  ...   

     PROGRESS Score Gender    Reported Race Special ED  ELA Status  \
0               3.0      M  BlackAfricanAme          Y          EO   
1               4.0      M  BlackAfricanAme          Y          EO   
2               4.0      M  BlackAfricanAme          Y          EO   
3               4.0      M  BlackAfricanAme          Y          EO   
4               NaN      M  BlackAfricanAme          Y          EO   
...             ...    ...              ...        ...         ...   
7737            NaN      F         Hispanic          N  Exited LEP   
7738            4.0      F         Hispanic          N  Exited LEP   
7739            2.0      F   TwoOrMoreRaces          Y          EO   
7740            1.0      F   TwoOrMoreRaces          Y          EO   
7741            4.0      F   TwoOrMoreRaces          Y          EO   

      Active Today  Language     Year  Smester  Quarter  
0                1        37  2021-22        2        3  
1                1        37  2021-22        2        3  
2                1        37  2021-22        2        3  
3                1        37  2021-22        2        3  
4                1        37  2021-22        2        3  
...            ...       ...      ...      ...      ...  
7737             1         1  2021-22        2        3  
7738             1         1  2021-22        2        3  
7739             0         0  2021-22        2        3  
7740             0         0  2021-22        2        3  
7741   

In [69]:
q3_willard_incorporated = pd.concat([old_willard,q3_willard],ignore_index=True)

In [70]:
q3_willard_incorporated

School  Grade Level  Student ID Period  \
0        Berkeley High School            9     2006000      1   
1        Berkeley High School            9     2006000      2   
2        Berkeley High School            9     2006000      3   
3        Berkeley High School            9     2006000      4   
4        Berkeley High School            9     2006000      5   
...                       ...          ...         ...    ...   
117539  Willard Middle School            8     2021187    NaN   
117540  Willard Middle School            8     2021187    NaN   
117541  Willard Middle School            8     2021326    NaN   
117542  Willard Middle School            8     2021326    NaN   
117543  Willard Middle School            8     2021326    NaN   

                 Course Q1 Grade   Grading Task  \
0         Physics 1 (P)       B-  Quarter Grade   
1               INE-CLC        A  Quarter Grade   
2       FrshSemHist (P)       B-  Quarter Grade   
3             Spanish I       B-  Quarter Grade   
4         English 1 (P)       D-  Quarter Grade   
...                 ...      ...            ...   
117539         Advisory      NaN            NaN   
117540         Advisory        4            NaN   
117541           Math 8       NG            NaN   
117542           Math 8       NG            NaN   
117543   Math 8 Support       NG            NaN   

       Fall STAR Reading Benchmark Cat. Fall STAR Reading Inst. Reading Level  \
0                                   NaN                                   NaN   
1                                   NaN                                   NaN   
2                                   NaN                                   NaN   
3                                   NaN                                   NaN   
4                                   NaN                                   NaN   
...                                 ...                                   ...   
117539                              NaN                                   NaN   
117540                              NaN                                   NaN   
117541                              NaN                                   NaN   
117542                              NaN                                   NaN   
117543                              NaN                                   NaN   

       Fall STAR Math Benchmark Cat.  ... Task Term Name  Course Num  \
0                                NaN  ...  NaN       NaN         NaN   
1                                NaN  ...  NaN       NaN         NaN   
2                                NaN  ...  NaN       NaN         NaN   
3                                NaN  ...  NaN       NaN         NaN   
4                                NaN  ...  NaN       NaN         NaN   
...                              ...  ...  ...       ...         ...   
117539                           NaN  ...  SBP        Q3        7925   
117540                           NaN  ...  HOW        Q3        7925   
117541                           NaN  ...  HOW        Q3        7033   
117542                           NaN  ...  SBP        Q3        7033   
117543                           NaN  ...  HOW        Q3        7036   

       Section Num Term ID Credit Credit Type Course ID PROGRESS Score  \
0              NaN     NaN    NaN         NaN       NaN            NaN   
1              NaN     NaN    NaN         NaN       NaN            NaN   
2              NaN     NaN    NaN         NaN       NaN            NaN   
3              NaN     NaN    NaN         NaN       NaN            NaN   
4              NaN     NaN    NaN         NaN       NaN            NaN   
...            ...     ...    ...         ...       ...            ...   
117539        12.0   622.0    NaN         NaN   55985.0            NaN   
117540        12.0   622.0    NaN         NaN   55985.0            4.0   
117541         3.0   622.0    NaN         NaN   55727.0            2.0   
117542         3.0   622.0    NaN         NaN   557

In [71]:
q3_willard_incorporated.to_excel("q3_willard_incorporated.xlsx")

**Q3 Willard incorporated Successfully**

In [73]:
q3_bhs = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\Quarter 3 Middle and High RT.xlsx", sheet_name="BHS")

q3_bhs_cols = q3_bhs.columns.to_list()

old_bhs = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\rt_fisher_data.xlsx", sheet_name="Q1 Grades")

old_bhs_cols= old_bhs.columns.to_list()

i=0
for index, col in enumerate(old_bhs_cols):
    if col in q3_bhs_cols:
        i+=1
        #print(f"col {index} of old data is in the new data")
    else:
        print(f"{col} col not found")

print(i)


Period col not found
Grading Task col not found
Fall STAR Reading Benchmark Cat. col not found
Fall STAR Reading Inst. Reading Level col not found
Fall STAR Math Benchmark Cat. col not found
Fall STAR Math Percentile Rank col not found
Ind Study col not found
Socio-Ec Disadv. col not found
504 col not found
McKV/Homeless col not found
Year col not found
Smester col not found
Quarter col not found
Last Name col not found
First Name col not found
Winter STAR Reading State Benchmark Cat. col not found
Winter STAR Math State Benchmark Cat. col not found
Full Name col not found
Growth Category ELA col not found
Vision Scholars 2021/2022 col not found
SLC col not found
27


In [74]:
q3_bhs['Year']='2021-22'
q3_bhs['Smester']=2
q3_bhs['Quarter']=3

In [75]:
q3_bhs

School  Grade Level          Last    First  Student ID  \
0      Berkeley High School           10  Tard-Meleder   Arthur     2021394   
1      Berkeley High School           10  Tard-Meleder   Arthur     2021394   
2      Berkeley High School           10  Tard-Meleder   Arthur     2021394   
3      Berkeley High School           10  Tard-Meleder   Arthur     2021394   
4      Berkeley High School           10  Tard-Meleder   Arthur     2021394   
...                     ...          ...           ...      ...         ...   
18711  Berkeley High School           12   Tapia-Mills  Violeta     2021385   
18712  Berkeley High School           12   Tapia-Mills  Violeta     2021385   
18713  Berkeley High School           12   Tapia-Mills  Violeta     2021385   
18714  Berkeley High School           12   Tapia-Mills  Violeta     2021385   
18715  Berkeley High School           12   Tapia-Mills  Violeta     2021385   

       In-School Suspension  Suspensions through 10/15  \
0                       NaN                        NaN   
1                       NaN                        NaN   
2                       NaN                        NaN   
3                       NaN                        NaN   
4                       NaN                        NaN   
...                     ...                        ...   
18711                   NaN                        NaN   
18712                   NaN                        NaN   
18713                   NaN                        NaN   
18714                   NaN                        NaN   
18715                   NaN                        NaN   

       Attendance 8/16 to 10/16                Course  \
0                        0.9775   SEI-IntgScience (P)   
1                        0.9775             SEI-ELD 3   
2                        0.9775     SEI-ELD Writing 3   
3                        0.9775     SEI-USHistory (P)   
4                        0.9775         EL Math 1 (P)   
...                         ...                   ...   
18711                    0.9750      SEI-WorldLit (P)   
18712                    0.9750       SEI-Writing (P)   
18713                    0.9750  AFAM-History 1/2 (P)   
18714                    0.9750            Math 3 (P)   
18715                    0.9750     Digital Photo (P)   

                          Teacher  ... Reported Race Special ED ELA Status  \
0            Hondros, Christopher  ...         White          N        LEP   
1      Maaze Merschdorf, Daniella  ...         White          N        LEP   
2      Maaze Merschdorf, Daniella  ...         White          N        LEP   
3               Stewart, Veronica  ...         White          N        LEP   
4                 Albrecht, Masha  ...         White          N        LEP   
...                           ...  ...           ...        ...        ...   
18711                 Maine, Anna  ...      Hispanic          N        LEP   
18712                 Maine, Anna  ...      Hispanic          N        LEP   
18713          Pritchard, Spencer  ...      Hispanic          N        LEP   
18714                Daly, Ashley  ...      Hispanic          N        LEP   
18715             Berent, Gabriel  ...      Hispanic          N        LEP   

      Active Today Language  student_teamName  Unnamed: 28     Year Smester  \
0                1       17                            NaN  2021-22       2   
1                1       17                            NaN  2021-22       2   
2                1       17                            NaN  2021-22       2   
3                1       17                            NaN  2021-22       2   
4                1       17                            NaN  2021-22       2   
...            ...      ...               ...          ...      ...     ...   
18711            1        1               MLP          NaN  2021-22       2   
18712            1        1               MLP          NaN  2021-22       2   
18713            1        1               

In [76]:
q3_bhs_incorporated = pd.concat([old_bhs,q3_bhs],ignore_index=True)

In [77]:
q3_bhs_incorporated

School  Grade Level  Student ID Period  \
0       Berkeley High School            9     2006000      1   
1       Berkeley High School            9     2006000      2   
2       Berkeley High School            9     2006000      3   
3       Berkeley High School            9     2006000      4   
4       Berkeley High School            9     2006000      5   
...                      ...          ...         ...    ...   
136255  Berkeley High School           12     2021385    NaN   
136256  Berkeley High School           12     2021385    NaN   
136257  Berkeley High School           12     2021385    NaN   
136258  Berkeley High School           12     2021385    NaN   
136259  Berkeley High School           12     2021385    NaN   

                      Course Q1 Grade   Grading Task  \
0              Physics 1 (P)       B-  Quarter Grade   
1                    INE-CLC        A  Quarter Grade   
2            FrshSemHist (P)       B-  Quarter Grade   
3                  Spanish I       B-  Quarter Grade   
4              English 1 (P)       D-  Quarter Grade   
...                      ...      ...            ...   
136255      SEI-WorldLit (P)        A            NaN   
136256       SEI-Writing (P)        A            NaN   
136257  AFAM-History 1/2 (P)        A            NaN   
136258            Math 3 (P)        C            NaN   
136259     Digital Photo (P)        A            NaN   

       Fall STAR Reading Benchmark Cat. Fall STAR Reading Inst. Reading Level  \
0                                   NaN                                   NaN   
1                                   NaN                                   NaN   
2                                   NaN                                   NaN   
3                                   NaN                                   NaN   
4                                   NaN                                   NaN   
...                                 ...                                   ...   
136255                              NaN                                   NaN   
136256                              NaN                                   NaN   
136257                              NaN                                   NaN   
136258                              NaN                                   NaN   
136259                              NaN                                   NaN   

       Fall STAR Math Benchmark Cat.  ... Course Num Section Num  Term ID  \
0                                NaN  ...        NaN         NaN      NaN   
1                                NaN  ...        NaN         NaN      NaN   
2                                NaN  ...        NaN         NaN      NaN   
3                                NaN  ...        NaN         NaN      NaN   
4                                NaN  ...        NaN         NaN      NaN   
...                              ...  ...        ...         ...      ...   
136255                           NaN  ...      EA18Y         1.0    602.0   
136256                           NaN  ...      EA73S         1.0    602.0   
136257                           NaN  ...      BB04Y         2.0    602.0   
136258                           NaN  ...      AC03Y         3.0    602.0   
136259                           NaN  ...      AG74Y         1.0    602.0   

       Credit Credit Type Course ID PROGRESS Score Active Today  \
0         NaN         NaN       NaN            NaN          NaN   
1         NaN         NaN       NaN            NaN          NaN   
2         NaN         NaN       NaN            NaN          NaN   
3         NaN         NaN       NaN            NaN          NaN   
4         NaN         NaN       NaN            NaN          NaN   
...       ...         ...       ...            ...          ...   
136255                      53846.0              A          1.0   
136256                      53852.0              A          1.0   
136257                      53952.0              A          1.0   
136258      

In [78]:
q3_bhs_incorporated.to_excel("q3_bhs_incorporated.xlsx")

**Q3 BHS successfully incorporated**

In [35]:
# T1 2021-22 new data just has more schools. lets find them and add them to old data.

In [36]:
old = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\rt_fisher_data.xlsx", sheet_name="TK-5")

In [37]:
old_schools=(old["School"].unique())

In [38]:
len(old_schools)

20

In [39]:
new = old = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\Elementary_Middle T1 21_22.xlsx", sheet_name="Sheet1")

In [40]:
new_schools=new["School"].unique()

In [41]:
len(new_schools)

17

In [42]:
for school in new_schools:
    if school not in old_schools:
        print(f"{school} was missing in old data")
#     else:
#         print(f"{school} is in old data")

In [43]:
len(old[old["School"]=="Berkeley Arts Magnet Elementary School"])

384

In [44]:
len(new[new["School"]=="Berkeley Arts Magnet Elementary School"])

384

In [45]:
old_cols=old.columns.to_list()

In [46]:
old_cols

['School',
 'Grade Level',
 'Teacher',
 'Student ID',
 'Last Name',
 'First Name',
 'Gender',
 'Reported Race',
 'Student Is Special Ed?',
 504.0,
 'English Proficiency',
 'Language',
 'SED from CALPADS',
 'McKV/ Homeless',
 'Suspensions through 10/25',
 'Attendance through 10/15',
 'Report Card: English TCRWP',
 'Report Card: English TCRWP level',
 'Report Card: Spanish TCRWP',
 'Report Card: Spanish TCRWP level',
 'Report Card: Op & Alg Thinking',
 'Report Card: Num & Ops in Base Ten',
 'Report Card: Measurement and Data',
 'Report Card: Geometry',
 'Report Card: Math Fluency',
 'STAR Reading District BC Name',
 'STAR Reading Instructional Reading Level',
 'STAR Reading Scaled Score',
 'STAR Math Spanish?',
 'STAR Math District BC Name',
 'STAR Math Percentile Rank',
 'STAR Math Scaled Score',
 'IDEL Instructional Level',
 'Dibels Composite Score',
 'Dibels Composite Level',
 'Math Benchmark Percent Correct',
 'Math Benchmark Performance Level']

In [47]:
new_cols= new.columns.to_list()

In [48]:
new_cols

['School',
 'Grade Level',
 'Teacher',
 'Student ID',
 'Last Name',
 'First Name',
 'Gender',
 'Reported Race',
 'Student Is Special Ed?',
 504.0,
 'English Proficiency',
 'Language',
 'SED from CALPADS',
 'McKV/ Homeless',
 'Suspensions through 10/25',
 'Attendance through 10/15',
 'Report Card: English TCRWP',
 'Report Card: English TCRWP level',
 'Report Card: Spanish TCRWP',
 'Report Card: Spanish TCRWP level',
 'Report Card: Op & Alg Thinking',
 'Report Card: Num & Ops in Base Ten',
 'Report Card: Measurement and Data',
 'Report Card: Geometry',
 'Report Card: Math Fluency',
 'STAR Reading District BC Name',
 'STAR Reading Instructional Reading Level',
 'STAR Reading Scaled Score',
 'STAR Math Spanish?',
 'STAR Math District BC Name',
 'STAR Math Percentile Rank',
 'STAR Math Scaled Score',
 'IDEL Instructional Level',
 'Dibels Composite Score',
 'Dibels Composite Level',
 'Math Benchmark Percent Correct',
 'Math Benchmark Performance Level']

In [49]:
len(old_cols)

37

In [50]:
len(new_cols)

37

In [51]:
longfellow=new[new["School"]=="Longfellow Magnet Middle School"]

In [52]:
len(longfellow)

472

In [53]:
mlk=new[new["School"]=="Martin Luther King Middle School"]

In [54]:
len(mlk)

910

In [55]:
willard=new[new["School"]=="Willard Middle School"]

In [56]:
len(willard)

598

In [57]:
new_schools_t1 = pd.concat([longfellow,mlk,willard],ignore_index=True)

In [58]:
len(new_schools_t1)

1980

In [59]:
all_schools_t1 = pd.concat([old,new_schools_t1], ignore_index=True)

In [60]:
all_schools_t1

School Grade Level         Teacher  \
0     Berkeley Arts Magnet Elementary School           K  Stroik, Sophia   
1     Berkeley Arts Magnet Elementary School           K  Stroik, Sophia   
2     Berkeley Arts Magnet Elementary School           K  Stroik, Sophia   
3     Berkeley Arts Magnet Elementary School           K  Stroik, Sophia   
4     Berkeley Arts Magnet Elementary School           K  Stroik, Sophia   
...                                      ...         ...             ...   
7819                   Willard Middle School         8.0             NaN   
7820                   Willard Middle School         8.0             NaN   
7821                   Willard Middle School         8.0             NaN   
7822                   Willard Middle School         8.0             NaN   
7823                   Willard Middle School         8.0             NaN   

      Student ID         Last Name First Name Gender Reported Race  \
0      2020428.0           Adelman     Margot      F         White   
1      2020105.0          Andrizzi    Liliana      F        Latinx   
2      2020091.0            Arnold        Aya      F         White   
3      2020130.0            Benton    Charles      M         White   
4      2020653.0         Berkowitz       Levi      M         White   
...          ...               ...        ...    ...           ...   
7819   2015145.0                Wu    Cynthia      F         Asian   
7820   2014372.0              Xiao      Tasya      F         Asian   
7821   2007559.0          Zabarsky     Simone      F        Latinx   
7822   2007554.0            Zoidis        Max      M         White   
7823   2007553.0  Zubeldia-Lippman      Diego      M        Latinx   

     Student Is Special Ed? 504.0  ... STAR Reading Scaled Score  \
0                         N     N  ...                       NaN   
1                         N     N  ...                       NaN   
2                         N     N  ...                       NaN   
3                         N     N  ...                       NaN   
4                         N     N  ...                       NaN   
...                     ...   ...  ...                       ...   
7819                      N     N  ...                    1309.0   
7820                      N     N  ...                    1154.0   
7821                      N     N  ...                    1231.0   
7822                      N     N  ...                    1126.0   
7823                      N     N  ...                     908.0   

     STAR Math Spanish? STAR Math District BC Name STAR Math Percentile Rank  \
0                   NaN                        NaN                       NaN   
1                   NaN                        NaN                       NaN   
2                   NaN                        NaN                       NaN   
3                   NaN                        NaN                       NaN   
4                   NaN                        NaN                       NaN   
...                 ...                        ...                       ...   
7819                NaN         At/Above Benchmark                      41.0   
7820                NaN         At/Above Benchmark                      74.0   
7821                NaN         At/Above Benchmark                      53.0   
7822                NaN         At/Above Benchmark                      71.0   
7823                NaN         At/Above Benchmark                      64.0   

      STAR Math Scaled Score  IDEL Instructional Level Dibels Composite Score  \
0                        NaN                       NaN                  327.0   
1                        NaN                       NaN                  275.0   
2                        NaN                       NaN                  302.0   
3                        NaN                       NaN                  328.0   
4                        NaN                       NaN                  332.0   
...                 

In [61]:
pip install xlsxwriter


Note: you may need to restart the kernel to use updated packages.


In [62]:
all_schools_t1.to_excel(r"output.xlsx",engine='xlsxwriter')

In [63]:
len(all_schools_t1["School"].unique())

17

# Elementary T2 Incorporation

In [64]:
old = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\rt_fisher_data.xlsx", sheet_name="TK-5")

In [65]:
old.head()

School Grade Level  Student ID Gender  \
0  Berkeley Arts Magnet Elementary School           K     2020428      F   
1  Berkeley Arts Magnet Elementary School           K     2020105      F   
2  Berkeley Arts Magnet Elementary School           K     2020091      F   
3  Berkeley Arts Magnet Elementary School           K     2020130      M   
4  Berkeley Arts Magnet Elementary School           K     2020653      M   

  Reported Race Student Is Special Ed? 504 English Proficiency Language  \
0         White                      N   N                  EO      NaN   
1        Latinx                      N   N                  EO      NaN   
2         White                      N   N                  EO      NaN   
3         White                      N   N                  EO      NaN   
4         White                      N   N                  EO      NaN   

  SED from CALPADS  ...     Year  Trimester  Vision Scholars  \
0                N  ...  2021-22          1              NaN   
1                N  ...  2021-22          1              NaN   
2                N  ...  2021-22          1              NaN   
3                N  ...  2021-22          1              NaN   
4                N  ...  2021-22          1              NaN   

  Writing On Demand STAR Reading State BC Name  STAR Math State BC Name  \
0               NaN                         NaN                     NaN   
1               NaN                         NaN                     NaN   
2               NaN                         NaN                     NaN   
3               NaN                         NaN                     NaN   
4               NaN                         NaN                     NaN   

   Spanish Math  District BCL  Spanish Math District Benchmark Name  \
0                         NaN                                   NaN   
1                         NaN                                   NaN   
2                         NaN                                   NaN   
3                         NaN                                   NaN   
4                         NaN                                   NaN   

   Spanish Math Percentile Rank Spanish Math Scaled Score  
0                           NaN                       NaN  
1                           NaN                       NaN  
2                           NaN                       NaN  
3                           NaN                       NaN  
4                           NaN                       NaN  

[5 rows x 47 columns]

In [66]:
old_cols= old.columns.to_list()

old_cols

['School',
 'Grade Level',
 'Student ID',
 'Gender',
 'Reported Race',
 'Student Is Special Ed?',
 504,
 'English Proficiency',
 'Language',
 'SED from CALPADS',
 'McKV/ Homeless',
 'Suspensions through 10/25',
 'Attendance through 10/15',
 'Report Card: English TCRWP',
 'Report Card: English TCRWP level',
 'Report Card: Spanish TCRWP',
 'Report Card: Spanish TCRWP level',
 'Report Card: Op & Alg Thinking',
 'Report Card: Num & Ops in Base Ten',
 'Report Card: Measurement and Data',
 'Report Card: Geometry',
 'Report Card: Math Fluency',
 'STAR Reading District BC Name',
 'STAR Reading Instructional Reading Level',
 'STAR Reading Scaled Score',
 'STAR Math Spanish?',
 'STAR Math District BC Name',
 'STAR Math Percentile Rank',
 'STAR Math Scaled Score',
 'IDEL Instructional Level',
 'Dibels Composite Score',
 'Dibels Composite Level',
 'Math Benchmark Percent Correct',
 'Math Benchmark Performance Level',
 'Teacher',
 'Last Name',
 'First Name',
 'Year',
 'Trimester',
 'Vision Scholars

In [67]:
new = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\21_22 Data Sheets TK-12 RT.xlsx", sheet_name="Elementary T2")

In [68]:
new.head()

School Grade Level             Teacher  \
0  Thousand Oaks Elementary School         5.0    Gillis, Jennifer   
1      John Muir Elementary School         5.0     Rosenthal, Lisa   
2       Cragmont Elementary School          KG        Rosen, Adria   
3       Cragmont Elementary School         2.0  Herbertson, Janine   
4      John Muir Elementary School         5.0     Rosenthal, Lisa   

   Student ID       Last Name First Name Gender Reported Race  \
0   2013206.0           Abbas   Muhammad      M         Asian   
1   2010668.0  Abcarian-Scott    Anahita      F        Latinx   
2   2020100.0        Abdallah     Shatha      F         White   
3   2016531.0        Abdallah     Shayma      F         White   
4   2018595.0    Abdel Rahman      Asser      M         White   

  Student Is Special Ed?     504.0  ... STAR Math Spanish?  \
0                    NaN       NaN  ...                NaN   
1                      Y  504 Plan  ...                NaN   
2                    NaN       NaN  ...                NaN   
3                    NaN       NaN  ...                NaN   
4                    NaN       NaN  ...                NaN   

  Spanish Math  District BCL Spanish Math District Benchmark Name  \
0                        NaN                                  NaN   
1                        NaN                                  NaN   
2                        NaN                                  NaN   
3                        NaN                                  NaN   
4                        NaN                                  NaN   

  Spanish Math Percentile Rank Spanish Math Scaled Score  \
0                          NaN                       NaN   
1                          NaN                       NaN   
2                          NaN                       NaN   
3                          NaN                       NaN   
4                          NaN                       NaN   

   IDEL Instructional Level  Dibels Composite Score Dibels Composite Level  \
0                       NaN                     NaN                    NaN   
1                       NaN                     NaN                    NaN   
2                       NaN                   341.0   Well Below Benchmark   
3                       NaN                   380.0        Below Benchmark   
4                       NaN                     NaN                    NaN   

  Math Benchmark Percent Correct Math Benchmark Performance Level  
0                            NaN                              NaN  
1                            NaN                              NaN  
2                            NaN                              NaN  
3                         0.4872      Needing Significant Support  
4                            NaN                              NaN  

[5 rows x 45 columns]

In [69]:
new=new.rename(columns={"Suspensions through 3/4/22":"Suspensions through 10/25","Attendance through 3/4/22":"Attendance through 10/15"})

In [70]:
new_cols = new.columns.to_list()
new_cols

['School',
 'Grade Level',
 'Teacher',
 'Student ID',
 'Last Name',
 'First Name',
 'Gender',
 'Reported Race',
 'Student Is Special Ed?',
 504.0,
 'English Proficiency',
 'Language',
 'SED from CALPADS',
 'McKV/ Homeless',
 'Vision Scholars',
 'Suspensions through 10/25',
 'Attendance through 10/15',
 'Writing On Demand',
 'Report Card: English TCRWP',
 'Report Card: English TCRWP level',
 'Report Card: Spanish TCRWP',
 'Report Card: Spanish TCRWP level',
 'Report Card: Op & Alg Thinking',
 'Report Card: Num & Ops in Base Ten',
 'Report Card: Measurement and Data',
 'Report Card: Geometry',
 'Report Card: Math Fluency',
 'STAR Reading District BC Name',
 'STAR Reading State BC Name ',
 'STAR Reading Instructional Reading Level',
 'STAR Reading Scaled Score',
 'STAR Math District BC Name',
 'STAR Math State BC Name',
 'STAR Math Percentile Rank',
 'STAR Math Scaled Score',
 'STAR Math Spanish?',
 'Spanish Math  District BCL',
 'Spanish Math District Benchmark Name',
 'Spanish Math Perc

In [71]:
new["Year"] = '2021-22'
new["Trimester"]  = 2

In [72]:
new.head()

School Grade Level             Teacher  \
0  Thousand Oaks Elementary School         5.0    Gillis, Jennifer   
1      John Muir Elementary School         5.0     Rosenthal, Lisa   
2       Cragmont Elementary School          KG        Rosen, Adria   
3       Cragmont Elementary School         2.0  Herbertson, Janine   
4      John Muir Elementary School         5.0     Rosenthal, Lisa   

   Student ID       Last Name First Name Gender Reported Race  \
0   2013206.0           Abbas   Muhammad      M         Asian   
1   2010668.0  Abcarian-Scott    Anahita      F        Latinx   
2   2020100.0        Abdallah     Shatha      F         White   
3   2016531.0        Abdallah     Shayma      F         White   
4   2018595.0    Abdel Rahman      Asser      M         White   

  Student Is Special Ed?     504.0  ... Spanish Math District Benchmark Name  \
0                    NaN       NaN  ...                                  NaN   
1                      Y  504 Plan  ...                                  NaN   
2                    NaN       NaN  ...                                  NaN   
3                    NaN       NaN  ...                                  NaN   
4                    NaN       NaN  ...                                  NaN   

  Spanish Math Percentile Rank Spanish Math Scaled Score  \
0                          NaN                       NaN   
1                          NaN                       NaN   
2                          NaN                       NaN   
3                          NaN                       NaN   
4                          NaN                       NaN   

  IDEL Instructional Level Dibels Composite Score  Dibels Composite Level  \
0                      NaN                    NaN                     NaN   
1                      NaN                    NaN                     NaN   
2                      NaN                  341.0    Well Below Benchmark   
3                      NaN                  380.0         Below Benchmark   
4                      NaN                    NaN                     NaN   

   Math Benchmark Percent Correct Math Benchmark Performance Level     Year  \
0                             NaN                              NaN  2021-22   
1                             NaN                              NaN  2021-22   
2                             NaN                              NaN  2021-22   
3                          0.4872      Needing Significant Support  2021-22   
4                             NaN                              NaN  2021-22   

  Trimester  
0         2  
1         2  
2         2  
3         2  
4         2  

[5 rows x 47 columns]

In [73]:
len(new)

3868

In [74]:
i=0
for index, col in enumerate(old_cols):
    if col in new_cols:
        i+=1
        print(f"col {index} of old data is in the new data")

col 0 of old data is in the new data
col 1 of old data is in the new data
col 2 of old data is in the new data
col 3 of old data is in the new data
col 4 of old data is in the new data
col 5 of old data is in the new data
col 6 of old data is in the new data
col 7 of old data is in the new data
col 8 of old data is in the new data
col 9 of old data is in the new data
col 10 of old data is in the new data
col 11 of old data is in the new data
col 12 of old data is in the new data
col 13 of old data is in the new data
col 14 of old data is in the new data
col 15 of old data is in the new data
col 16 of old data is in the new data
col 17 of old data is in the new data
col 18 of old data is in the new data
col 19 of old data is in the new data
col 20 of old data is in the new data
col 21 of old data is in the new data
col 22 of old data is in the new data
col 23 of old data is in the new data
col 24 of old data is in the new data
col 25 of old data is in the new data
col 26 of old data is 

In [75]:
t2_incorporated = pd.concat([old,new],ignore_index=True)

In [76]:
t2_incorporated

School Grade Level  Student ID Gender  \
0      Berkeley Arts Magnet Elementary School           K   2020428.0      F   
1      Berkeley Arts Magnet Elementary School           K   2020105.0      F   
2      Berkeley Arts Magnet Elementary School           K   2020091.0      F   
3      Berkeley Arts Magnet Elementary School           K   2020130.0      M   
4      Berkeley Arts Magnet Elementary School           K   2020653.0      M   
...                                       ...         ...         ...    ...   
13575         Sylvia Mendez Elementary School          KG   2020322.0      F   
13576             Malcolm X Elementary School         5.0   2012758.0      F   
13577             Malcolm X Elementary School         1.0   2019075.0      F   
13578             Ruth Acty Elementary School         5.0   2009877.0      M   
13579             Ruth Acty Elementary School         5.0   2009878.0      M   

      Reported Race Student Is Special Ed?  504 English Proficiency Language  \
0             White                      N    N                  EO      NaN   
1            Latinx                      N    N                  EO      NaN   
2             White                      N    N                  EO      NaN   
3             White                      N    N                  EO      NaN   
4             White                      N    N                  EO      NaN   
...             ...                    ...  ...                 ...      ...   
13575        Latinx                    NaN  NaN                 LEP  Spanish   
13576         White                    NaN  NaN                  EO      NaN   
13577         White                    NaN  NaN                  EO      NaN   
13578         White                    NaN  NaN                  EO      NaN   
13579         White                      Y  NaN                  EO      NaN   

      SED from CALPADS  ...     Year  Trimester  Vision Scholars  \
0                    N  ...  2021-22          1              NaN   
1                    N  ...  2021-22          1              NaN   
2                    N  ...  2021-22          1              NaN   
3                    N  ...  2021-22          1              NaN   
4                    N  ...  2021-22          1              NaN   
...                ...  ...      ...        ...              ...   
13575                Y  ...  2021-22          2              NaN   
13576              NaN  ...  2021-22          2              NaN   
13577              NaN  ...  2021-22          2              NaN   
13578              NaN  ...  2021-22          2              NaN   
13579              NaN  ...  2021-22          2              NaN   

      Writing On Demand STAR Reading State BC Name  STAR Math State BC Name  \
0                   NaN                         NaN                     NaN   
1                   NaN                         NaN                     NaN   
2                   NaN                         NaN                     NaN   
3                   NaN                         NaN                     NaN   
4                   NaN                         NaN                     NaN   
...                 ...                         ...                     ...   
13575               4.0                         NaN                     NaN   
13576               3.0          At/Above Benchmark           Intervention    
13577               3.0                         NaN                     NaN   
13578               3.5          At/Above Benchmark      At/Above Benchmark   
13579               2.0                    On Watch      At/Above Benchmark   

       Spanish Math  District BCL  Spanish Math District Benchmark Name  \
0                             NaN                                   NaN   
1                             NaN                                   NaN   
2                             NaN                                   NaN   
3                             NaN                  

In [77]:
t2_incorporated.to_excel(r"output.xlsx",engine='xlsxwriter')

In [78]:
len(old["School"].unique())==len(new["School"].unique())

False

In [79]:
len(new["School"].unique())

15

In [80]:
new

School Grade Level              Teacher  \
0     Thousand Oaks Elementary School         5.0     Gillis, Jennifer   
1         John Muir Elementary School         5.0      Rosenthal, Lisa   
2          Cragmont Elementary School          KG         Rosen, Adria   
3          Cragmont Elementary School         2.0   Herbertson, Janine   
4         John Muir Elementary School         5.0      Rosenthal, Lisa   
...                               ...         ...                  ...   
3863  Sylvia Mendez Elementary School          KG        Lourdes Rivas   
3864      Malcolm X Elementary School         5.0  McDaniels, Lachelle   
3865      Malcolm X Elementary School         1.0  Richerson, Kathleen   
3866      Ruth Acty Elementary School         5.0        Rohr, Abigail   
3867      Ruth Acty Elementary School         5.0         Khanna, Arun   

      Student ID       Last Name First Name Gender Reported Race  \
0      2013206.0           Abbas   Muhammad      M         Asian   
1      2010668.0  Abcarian-Scott    Anahita      F        Latinx   
2      2020100.0        Abdallah     Shatha      F         White   
3      2016531.0        Abdallah     Shayma      F         White   
4      2018595.0    Abdel Rahman      Asser      M         White   
...          ...             ...        ...    ...           ...   
3863   2020322.0  Zubieta-Coreas    Juliett      F        Latinx   
3864   2012758.0          Zucker      Amira      F         White   
3865   2019075.0          Zucker       Anya      F         White   
3866   2009877.0  Zykov-Chisholm    Aleksei      M         White   
3867   2009878.0  Zykov-Chisholm    Nikolai      M         White   

     Student Is Special Ed?     504.0  ...  \
0                       NaN       NaN  ...   
1                         Y  504 Plan  ...   
2                       NaN       NaN  ...   
3                       NaN       NaN  ...   
4                       NaN       NaN  ...   
...                     ...       ...  ...   
3863                    NaN       NaN  ...   
3864                    NaN       NaN  ...   
3865                    NaN       NaN  ...   
3866                    NaN       NaN  ...   
3867                      Y       NaN  ...   

     Spanish Math District Benchmark Name Spanish Math Percentile Rank  \
0                                     NaN                          NaN   
1                                     NaN                          NaN   
2                                     NaN                          NaN   
3                                     NaN                          NaN   
4                                     NaN                          NaN   
...                                   ...                          ...   
3863                                  NaN                          NaN   
3864                                  NaN                          NaN   
3865                                  NaN                          NaN   
3866                                  NaN                          NaN   
3867                                  NaN                          NaN   

     Spanish Math Scaled Score IDEL Instructional Level  \
0                          NaN                      NaN   
1                          NaN                      NaN   
2                          NaN                      NaN   
3                          NaN                      NaN   
4                          NaN                      NaN   
...                        ...                      ...   
3863                       NaN                Benchmark   
3864                       NaN                      NaN   
3865                       NaN                      NaN   
3866                       NaN                      NaN   
3867                       NaN                      NaN   

     Dibels Composite Score  Dibels Composite Level  \
0                       NaN                     NaN   
1                       NaN                     NaN   
2        

In [81]:
len(old["Student ID"].unique())

5927

In [82]:
old=t2_incorporated[t2_incorporated["Trimester"]==1]

In [83]:
len(old)

5844

In [84]:
new=t2_incorporated[t2_incorporated["Trimester"]==2]

In [85]:
len(new)

7736

#  High School Incorporation

In [138]:
a = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\rt_fisher_data.xlsx", sheet_name="Q1 Grades")

In [139]:
a.columns.to_list()

['School',
 'Grade Level',
 'Student ID',
 'Period',
 'Course',
 'Q1 Grade',
 'Grading Task',
 'Fall STAR Reading Benchmark Cat.',
 'Fall STAR Reading Inst. Reading Level',
 'Fall STAR Math Benchmark Cat.',
 'Fall STAR Math Percentile Rank',
 'Attendance 8/16 to 10/16',
 'Suspensions through 10/15',
 'Reported Race',
 'Special ED',
 'ELA Status',
 'Gender',
 'Ind Study',
 'Socio-Ec Disadv.',
 504,
 'McKV/Homeless',
 'Year',
 'Smester',
 'Quarter']

# Vision Scholars

## BAM

In [69]:
import pandas as pd

In [76]:
vs_bam= pd.read_excel(r"C:\\Users\\Hussam\\Desktop\\RT Fisher\\VISION SCHOLAR student list.xlsx", sheet_name="BAM")

In [78]:
vs_bam.head()

School  Grade Level             Teacher  \
0  Berkeley Arts Magnet Elementary School            1  Palmer-Ghose, Ruby   
1  Berkeley Arts Magnet Elementary School            1  Palmer-Ghose, Ruby   
2  Berkeley Arts Magnet Elementary School            1     Wright, Suzanne   
3  Berkeley Arts Magnet Elementary School            1      Thomas, Marcie   
4  Berkeley Arts Magnet Elementary School            2   Hamilton, Patrick   

   Student ID Unnamed: 4 Unnamed: 5        Last Name First Name Gender  \
0     2017847          ,   2017847,          Conerly    Sy'Aire      F   
1     2019832          ,   2019832,          Edwards     Josiah      M   
2     2021137          ,   2021137,        Patterson       Leon      M   
3     2019826          ,   2019826,       Hill-Davis    Safiyah      F   
4     2017671          ,   2017671,  Garrett-Patrick    Terence      M   

  Reported Race  ... STAR Math Spanish?  Spanish Math  District BCL  \
0      Black/AA  ...                NaN                         NaN   
1      Black/AA  ...                NaN                         NaN   
2      Black/AA  ...                NaN                         NaN   
3      MultiEth  ...                NaN                         NaN   
4      Black/AA  ...                NaN                         NaN   

  Spanish Math District Benchmark Name Spanish Math Percentile Rank  \
0                                  NaN                          NaN   
1                                  NaN                          NaN   
2                                  NaN                          NaN   
3                                  NaN                          NaN   
4                                  NaN                          NaN   

  Spanish Math Scaled Score IDEL Instructional Level Dibels Composite Score  \
0                       NaN                      NaN                  391.0   
1                       NaN                      NaN                  353.0   
2                       NaN                      NaN                    NaN   
3                       NaN                      NaN                  380.0   
4                       NaN                      NaN                  348.0   

   Dibels Composite Level  Math Benchmark Percent Correct  \
0            At Benchmark                             NaN   
1    Well Below Benchmark                             NaN   
2                     NaN                             NaN   
3         Below Benchmark                             NaN   
4    Well Below Benchmark                           0.641   

   Math Benchmark Performance Level  
0                               NaN  
1                               NaN  
2                               NaN  
3                               NaN  
4                       Approaching  

[5 rows x 47 columns]

In [79]:
vs_bam_ids=vs_bam["Student ID"].tolist()

In [80]:
len(vs_bam_ids)

19

In [81]:
master_sheet = pd.read_excel(r"C:\\Users\\Hussam\\Desktop\\RT Fisher\\rt_fisher_data.xlsx", sheet_name="TK-5")

In [82]:
master_sheet.head(2)

School Grade Level  Student ID Gender  \
0  Berkeley Arts Magnet Elementary School           K     2020428      F   
1  Berkeley Arts Magnet Elementary School           K     2020105      F   

  Reported Race Student Is Special Ed? 504 English Proficiency Language  \
0         White                      N   N                  EO      NaN   
1        Latinx                      N   N                  EO      NaN   

  SED from CALPADS  ...     Year  Trimester  Vision Scholars  \
0                N  ...  2021-22          1              NaN   
1                N  ...  2021-22          1              NaN   

  Writing On Demand STAR Reading State BC Name  STAR Math State BC Name  \
0               NaN                         NaN                     NaN   
1               NaN                         NaN                     NaN   

   Spanish Math  District BCL  Spanish Math District Benchmark Name  \
0                         NaN                                   NaN   
1                         NaN                                   NaN   

   Spanish Math Percentile Rank Spanish Math Scaled Score  
0                           NaN                       NaN  
1                           NaN                       NaN  

[2 rows x 47 columns]

In [83]:
master_sheet_ids = master_sheet["Student ID"].tolist()

In [84]:
len(master_sheet_ids)

9712

In [85]:
counter=0
for vs_bam_id in vs_bam_ids:
    if vs_bam_id in master_sheet_ids:
        rowIndexes = master_sheet.index[master_sheet["Student ID"]==vs_bam_id]
        for rowIndex in rowIndexes:
            master_sheet.loc[rowIndex, 'Vision Scholars'] = 1

In [86]:
master_sheet["Vision Scholars"].value_counts()

X    87
1    38
Name: Vision Scholars, dtype: int64

## Malx

In [89]:
vs_malx= pd.read_excel(r"C:\\Users\\Hussam\\Desktop\\RT Fisher\\VISION SCHOLAR student list.xlsx", sheet_name="Malcolm X")
vs_malx_ids=vs_malx["Student ID"].tolist()
print(len(vs_malx))
counter=0
for vs_malx_id in vs_malx_ids:
    if vs_malx_id in master_sheet_ids:
        rowIndexes = master_sheet.index[master_sheet["Student ID"]==vs_malx_id]
        for rowIndex in rowIndexes:
            master_sheet.loc[rowIndex, 'Vision Scholars'] = 1
print(master_sheet["Vision Scholars"].value_counts())

42
1    122
X     45
Name: Vision Scholars, dtype: int64


## Oxford

In [90]:
vs_ox= pd.read_excel(r"C:\\Users\\Hussam\\Desktop\\RT Fisher\\VISION SCHOLAR student list.xlsx", sheet_name="Oxford")
vs_ox_ids=vs_ox["Student ID"].tolist()
print(len(vs_ox_ids))
counter=0
for vs_ox_id in vs_ox_ids:
    if vs_ox_id in master_sheet_ids:
        rowIndexes = master_sheet.index[master_sheet["Student ID"]==vs_ox_id]
        for rowIndex in rowIndexes:
            master_sheet.loc[rowIndex, 'Vision Scholars'] = 1
print(master_sheet["Vision Scholars"].value_counts())

20
1    162
X     25
Name: Vision Scholars, dtype: int64


## Washington

In [91]:
vs_wash= pd.read_excel(r"C:\\Users\\Hussam\\Desktop\\RT Fisher\\VISION SCHOLAR student list.xlsx", sheet_name="Washington")
vs_wash_ids=vs_wash["Student ID"].tolist()
print(len(vs_wash_ids))
counter=0
for vs_wash_id in vs_wash_ids:
    if vs_wash_id in master_sheet_ids:
        rowIndexes = master_sheet.index[master_sheet["Student ID"]==vs_wash_id]
        for rowIndex in rowIndexes:
            master_sheet.loc[rowIndex, 'Vision Scholars'] = 1
print(master_sheet["Vision Scholars"].value_counts())

24
1    210
X      1
Name: Vision Scholars, dtype: int64


# Longfellow 

In [100]:
vs_long= pd.read_excel(r"C:\\Users\\Hussam\\Desktop\\RT Fisher\\VISION SCHOLAR student list.xlsx", sheet_name="Longfellow")
vs_long_ids=vs_long["Student ID"].tolist()
print(len(vs_long_ids))
c=0
for vs_long_id in vs_long_ids:
    if vs_long_id in master_sheet_ids:
        rowIndexes = master_sheet.index[master_sheet["Student ID"]==vs_long_id]
        for rowIndex in rowIndexes:
            master_sheet.loc[rowIndex, 'Vision Scholars'] = 1
            c+=1
print(master_sheet["Vision Scholars"].value_counts())
print(c)

699
1    262
X      1
Name: Vision Scholars, dtype: int64
699


**699 ids where unique are 52 and longfellow data only for T1 in master sheet**

In [101]:
master_sheet["Vision Scholars"].value_counts()

1    262
X      1
Name: Vision Scholars, dtype: int64

In [103]:
master_sheet["Vision Scholars"]=master_sheet["Vision Scholars"].fillna(0)

In [104]:
master_sheet["Vision Scholars"].value_counts()

0    9449
1     262
X       1
Name: Vision Scholars, dtype: int64

In [112]:
X_index= master_sheet.index[master_sheet["Vision Scholars"]=="X"]

In [113]:
master_sheet.loc[X_index,"Vision Scholars"]=0

In [114]:
master_sheet["Vision Scholars"].value_counts()

0    9450
1     262
Name: Vision Scholars, dtype: int64

In [116]:
master_sheet.head(1)

School Grade Level  Student ID Gender  \
0  Berkeley Arts Magnet Elementary School           K     2020428      F   

  Reported Race Student Is Special Ed? 504 English Proficiency Language  \
0         White                      N   N                  EO      NaN   

  SED from CALPADS  ...     Year  Trimester  Vision Scholars  \
0                N  ...  2021-22          1                0   

  Writing On Demand STAR Reading State BC Name  STAR Math State BC Name  \
0               NaN                         NaN                     NaN   

   Spanish Math  District BCL  Spanish Math District Benchmark Name  \
0                         NaN                                   NaN   

   Spanish Math Percentile Rank Spanish Math Scaled Score  
0                           NaN                       NaN  

[1 rows x 47 columns]

### Reading Level Data 

In [139]:
vs_rld= pd.read_excel(r"C:\\Users\\Hussam\\Desktop\\RT Fisher\\VISION SCHOLAR student list.xlsx", sheet_name="Reading level data")
vs_rld_first=vs_rld["First "].tolist()
vs_rld_last = vs_rld["Student (K-3) Last "].tolist()
print(len(vs_rld_first))
print(len(vs_rld_last))
c=0
for vs_rld_name in zip(vs_rld_first,vs_rld_last):
    if vs_rld_name in zip(master_sheet["First Name"].tolist(),master_sheet["Last Name"].tolist()):
        rowIndexes = master_sheet.index[master_sheet["First Name"]==vs_rld_name]
        for rowIndex in rowIndexes:
            master_sheet.loc[rowIndex, 'Vision Scholars'] = 1
        c+=1
print(master_sheet["Vision Scholars"].value_counts())
print(c)

70
70
0    9263
1     449
Name: Vision Scholars, dtype: int64
70


In [275]:
data=pd.read_excel(r"C:\\Users\\Hussam\Desktop\\RT Fisher\\vision_implemented_tk_5.xlsx")

In [276]:
data["Vision Scholars"].value_counts()

0    9450
1     262
Name: Vision Scholars, dtype: int64

In [277]:
data["First Name"].value_counts(dropna=False)

NaN           3864
William         31
Samuel          29
Oliver          29
Sophia          27
              ... 
Zack             1
Christsean       1
Hildegard        1
Kaelin           1
Aleksei          1
Name: First Name, Length: 2946, dtype: int64

In [278]:
data["First Name"]=data["First Name"].fillna(" ")

In [279]:
data["First Name"].value_counts()

              3864
William         31
Samuel          29
Oliver          29
Sophia          27
              ... 
Zack             1
Christsean       1
Hildegard        1
Kaelin           1
Aleksei          1
Name: First Name, Length: 2946, dtype: int64

In [282]:
data["First Name"]=data["First Name"].astype(object)

In [286]:
data["First Name"].info

<bound method Series.info of 0              
1              
2              
3              
4              
         ...   
9707    Juliett
9708      Amira
9709       Anya
9710    Aleksei
9711    Nikolai
Name: First Name, Length: 9712, dtype: object>

In [287]:
data["Last Name"]=data["Last Name"].fillna(" ")

In [288]:
data["Last Name"].value_counts()

                   3864
Johnson              32
Lee                  27
Smith                25
Davis                24
                   ... 
Chess                 1
Cheung Williams       1
Chew                  1
Chien                 1
Guerreiro Ramos       1
Name: Last Name, Length: 3570, dtype: int64

In [295]:
vs_rld= pd.read_excel(r"C:\\Users\\Hussam\\Desktop\\RT Fisher\\VISION SCHOLAR student list.xlsx", sheet_name="Reading level data")
vs_rld_first=vs_rld["First "].tolist()
vs_rld_last = vs_rld["Student (K-3) Last "].tolist()
vs_rld_names=[f+" "+l for f,l in zip(vs_rld_first,vs_rld_last)]
c=0

for index,row in data.iterrows():
    name=(row["First Name"])+" " +(row["Last Name"])
    data.loc[index,"full name"]=name
    if name in vs_rld_names:
        rowIndexes = data.index[data["full name"]==name]
        for rowIndex in rowIndexes:
            data.loc[rowIndex, 'Vision Scholars'] = 1
        c+=1
print(data["Vision Scholars"].value_counts())
print(c)


0    9450
1     262
Name: Vision Scholars, dtype: int64
70


In [292]:
vs_rld_names

["Sy'Aire Conerly",
 'Josiah Edwards',
 'Leon Patterson',
 'Safiyah Hill-Davis',
 'Terence Garrett-Patrick',
 'Michaela Broadway',
 'Giovanni Evans',
 'Evelyn Martinez Zarazua',
 "Ny'Aira Hatchett",
 'James Boyd',
 'Marniya Dennis',
 'Aubrei Reed',
 'Khodey Morgan',
 'Moulay Ahmed Cherkaoui',
 'John Alvarado Navarro',
 'Brooklyn Stinson',
 'Giovanni Vega',
 'Jesse Yarbrough',
 'Summiyah Bess',
 'Jacquelyn Gonzalez Cruz',
 'Isaiah Knox',
 'Kendall Payton',
 'Cesar Prieto',
 'Israel Wiggins',
 'Kodi Williams',
 'Jasiri Yarbrough',
 'Carolyn Burnett',
 'Maliya Franklin',
 'Elias Gonzalez Velazquez',
 'Anari Johnson',
 'Amarie Kent',
 'Tiana Killensworth',
 'Isaiah Prieto',
 'Jordyn Reid',
 'Luis Reyes Ayala',
 'Miguel Reyes Ayala',
 'Kiyomi Woods',
 'Evelyn Barraza Navarrete',
 'Kaeo Jones',
 'Jasmine May',
 'Ivan Robles',
 'Princeugene Rockwell',
 'Braelyn Figueroa',
 'Brielle Figueroa',
 'Lorenzo Garcia-Vega',
 'Amayah Jaymes-Rodriguez',
 'Jahsiah Montaque',
 'Christian Taylor',
 'Jayde

In [220]:
data["name"].value_counts()

nannan    1
Name: name, dtype: int64

In [186]:
data

Unnamed: 0                                  School Grade Level  \
0              0  Berkeley Arts Magnet Elementary School           K   
1              1  Berkeley Arts Magnet Elementary School           K   
2              2  Berkeley Arts Magnet Elementary School           K   
3              3  Berkeley Arts Magnet Elementary School           K   
4              4  Berkeley Arts Magnet Elementary School           K   
...          ...                                     ...         ...   
9707        9707         Sylvia Mendez Elementary School          KG   
9708        9708             Malcolm X Elementary School           5   
9709        9709             Malcolm X Elementary School           1   
9710        9710             Ruth Acty Elementary School           5   
9711        9711             Ruth Acty Elementary School           5   

      Student ID Gender Reported Race Student Is Special Ed?  504  \
0        2020428      F         White                      N    N   
1        2020105      F        Latinx                      N    N   
2        2020091      F         White                      N    N   
3        2020130      M         White                      N    N   
4        2020653      M         White                      N    N   
...          ...    ...           ...                    ...  ...   
9707     2020322      F        Latinx                    NaN  NaN   
9708     2012758      F         White                    NaN  NaN   
9709     2019075      F         White                    NaN  NaN   
9710     2009877      M         White                    NaN  NaN   
9711     2009878      M         White                      Y  NaN   

     English Proficiency Language  ...     Year Trimester  Vision Scholars  \
0                     EO      NaN  ...  2021-22         1                0   
1                     EO      NaN  ...  2021-22         1                0   
2                     EO      NaN  ...  2021-22         1                0   
3                     EO      NaN  ...  2021-22         1                0   
4                     EO      NaN  ...  2021-22         1                0   
...                  ...      ...  ...      ...       ...              ...   
9707                 LEP  Spanish  ...  2021-22         2                0   
9708                  EO      NaN  ...  2021-22         2                0   
9709                  EO      NaN  ...  2021-22         2                0   
9710                  EO      NaN  ...  2021-22         2                0   
9711                  EO      NaN  ...  2021-22         2                0   

      Writing On Demand STAR Reading State BC Name  STAR Math State BC Name  \
0                   NaN                         NaN                     NaN   
1                   NaN                         NaN                     NaN   
2                   NaN                         NaN                     NaN   
3                   NaN                         NaN                     NaN   
4                   NaN                         NaN                     NaN   
...                 ...                         ...                     ...   
9707                  4                         NaN                     NaN   
9708                  3          At/Above Benchmark           Intervention    
9709                  3                         NaN                     NaN   
9710                3.5          At/Above Benchmark      At/Above Benchmark   
9711                  2                    On Watch      At/Above Benchmark   

     Spanish Math  District BCL  Spanish Math District Benchmark Name  \
0                           NaN                                   NaN   
1                           NaN                                   NaN   
2                           NaN                                   NaN   
3                           NaN                                   NaN   
4                           NaN                              

# Step UP

## Export 1

In [1]:
import pandas as pd

In [5]:
step_up_ex1= pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\STEP UP Academy student list.xlsx", sheet_name="Export 5.17.22")

In [6]:
step_up_ex1.head(1)

# PARENT FIRST NAME PARENT LAST NAME           MAILING ADDRESS      City  \
0  1.0          Janielle           Bailey  106 Alcatraz Ave. Unit.B  Berkeley   

  STATE    ZIP     PARENT/GUARDIAN EMAIL     PHONE 1  PHONE 2 LANGUAGE  \
0    CA  94702  JanielleBailey@gmail.com  5109047411      NaN  English   

   REGISTRATION  STUDENT FIRST NAME STUDENT LAST NAME  GENDER  \
0            2.0             Samaya            Kelley  Female   

          GRADE LEVEL               SCHOOL NAME SUPPLEMENTAL CLASS   \
0  Entering 8th Grade  Longfellow Middle School                 Yes   

  Parent Acknowledgement & Signature  
0                    Janielle Bailey

In [7]:
master_sheet = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\vision_implemented_tk_5.xlsx")

In [9]:
master_sheet.head(1)

Unnamed: 0                                  School Grade Level  Student ID  \
0           0  Berkeley Arts Magnet Elementary School           K     2020428   

  Gender Reported Race Student Is Special Ed? 504 English Proficiency  \
0      F         White                      N   N                  EO   

  Language  ...     Year Trimester  Vision Scholars  Writing On Demand  \
0      NaN  ...  2021-22         1                0                NaN   

  STAR Reading State BC Name  STAR Math State BC Name  \
0                         NaN                     NaN   

  Spanish Math  District BCL  Spanish Math District Benchmark Name  \
0                        NaN                                   NaN   

   Spanish Math Percentile Rank  Spanish Math Scaled Score  
0                           NaN                        NaN  

[1 rows x 48 columns]

In [10]:
master_sheet["Vision Scholars"].value_counts()

0    9450
1     262
Name: Vision Scholars, dtype: int64

In [12]:
step_up_ex1["STUDENT FIRST NAME"].head()

0    Samaya
1     Malik
2     Jason
3     Zahra
4     Tarik
Name: STUDENT FIRST NAME, dtype: object

In [13]:
step_up_ex1["STUDENT LAST NAME"].head()

0       Kelley
1       Kelley
2        Stean
3    Muwwakkil
4    Muwwakkil
Name: STUDENT LAST NAME, dtype: object

In [14]:
len(step_up_ex1)

45

In [19]:
f_name=step_up_ex1["STUDENT FIRST NAME"]

In [20]:
counter={}
for name in f_name:
    if name in counter:
        counter[name]+=1
    else:
        counter[name]=1

In [28]:
c=0
for value in counter.values():
    if value==2:
        c+=1
print(c)

4


In [29]:
len(step_up_ex1)-c

41

**41 unique names in step up export 1**
### Main Work for Export 1 Here

In [104]:
master_sheet = pd.read_excel(r"C:\Users\Hussam\Desktop\RT Fisher\vision_implemented_tk_5.xlsx")
master_sheet[["First Name", "Last Name"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   First Name  5848 non-null   object
 1   Last Name   5848 non-null   object
dtypes: object(2)
memory usage: 151.9+ KB


In [105]:
master_sheet["First Name"]=master_sheet["First Name"].fillna(" ")
master_sheet["First Name"]=master_sheet["First Name"].astype(str)
master_sheet["First Name"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 9712 entries, 0 to 9711
Series name: First Name
Non-Null Count  Dtype 
--------------  ----- 
9712 non-null   object
dtypes: object(1)
memory usage: 76.0+ KB


In [106]:
master_sheet["Last Name"]=master_sheet["Last Name"].fillna(" ")
master_sheet["Last Name"]=master_sheet["Last Name"].astype(str)
master_sheet["Last Name"]

0                     
1                     
2                     
3                     
4                     
             ...      
9707    Zubieta-Coreas
9708            Zucker
9709            Zucker
9710    Zykov-Chisholm
9711    Zykov-Chisholm
Name: Last Name, Length: 9712, dtype: object

In [107]:
master_sheet[["First Name", "Last Name"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9712 entries, 0 to 9711
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   First Name  9712 non-null   object
 1   Last Name   9712 non-null   object
dtypes: object(2)
memory usage: 151.9+ KB


In [108]:
step_up_ex1= pd.read_excel(r"C:\\Users\\Hussam\Desktop\\RT Fisher\\STEP UP Academy student list.xlsx", sheet_name="Export 5.17.22")
step_up_ex1_first=step_up_ex1["STUDENT FIRST NAME"].tolist()
step_up_ex1_last = step_up_ex1["STUDENT LAST NAME"].tolist()
step_up_ex1_names=[f+" "+l for f,l in zip(step_up_ex1_first,step_up_ex1_last)]
c=0

for index,row in master_sheet.iterrows():
    name=(row["First Name"]) + " " + (row["Last Name"])
    master_sheet.loc[index,"full name"]=name
    if name in step_up_ex1_names:
        rowIndexes = master_sheet.index[master_sheet["full name"]==name]
        for rowIndex in rowIndexes:
            if master_sheet.loc[rowIndex, "Vision Scholars"]==0:
                master_sheet.loc[rowIndex, 'Vision Scholars'] = 5
            if master_sheet.loc[rowIndex, "Vision Scholars"]==1:
                master_sheet.loc[rowIndex, 'Vision Scholars'] = 6
        c+=1
print(master_sheet["Vision Scholars"].value_counts())
print(c)

0    9428
1     260
5      22
6       2
Name: Vision Scholars, dtype: int64
24


## Export 2

In [109]:
step_up_ex2= pd.read_excel(r"C:\\Users\\Hussam\Desktop\\RT Fisher\\STEP UP Academy student list.xlsx", sheet_name="Export 5.24.22")
step_up_ex2_first=step_up_ex2["Student 1 Name:"].tolist()
step_up_ex2_last = step_up_ex2["Student Last"].tolist()
step_up_ex2_names=[f+" "+l for f,l in zip(step_up_ex2_first,step_up_ex2_last)]
c=0

for index,row in master_sheet.iterrows():
    name=(row["First Name"]) + " " + (row["Last Name"])
    master_sheet.loc[index,"full name"]=name
    if name in step_up_ex2_names:
        rowIndexes = master_sheet.index[master_sheet["full name"]==name]
        for rowIndex in rowIndexes:
            if master_sheet.loc[rowIndex, "Vision Scholars"]==0:
                master_sheet.loc[rowIndex, 'Vision Scholars'] = 5
            if master_sheet.loc[rowIndex, "Vision Scholars"]==1:
                master_sheet.loc[rowIndex, 'Vision Scholars'] = 6
        c+=1
print(master_sheet["Vision Scholars"].value_counts())
print(c)

0    9419
1     258
5      31
6       4
Name: Vision Scholars, dtype: int64
11


## Export 3

In [112]:
step_up_ex3= pd.read_excel(r"C:\\Users\\Hussam\Desktop\\RT Fisher\\STEP UP Academy student list.xlsx", sheet_name="Export 6.03.22")
step_up_ex3_first=step_up_ex3["Student 1 Name:"].tolist()
step_up_ex3_last = step_up_ex3["Student Last"].tolist()
step_up_ex3_names=[f+" "+l for f,l in zip(step_up_ex3_first,step_up_ex3_last)]
c=0

for index,row in master_sheet.iterrows():
    name=(row["First Name"]) + " " + (row["Last Name"])
    master_sheet.loc[index,"full name"]=name
    if name in step_up_ex3_names:
        rowIndexes = master_sheet.index[master_sheet["full name"]==name]
        for rowIndex in rowIndexes:
            if master_sheet.loc[rowIndex, "Vision Scholars"]==0:
                master_sheet.loc[rowIndex, 'Vision Scholars'] = 5
            if master_sheet.loc[rowIndex, "Vision Scholars"]==1:
                master_sheet.loc[rowIndex, 'Vision Scholars'] = 6
        c+=1
print(master_sheet["Vision Scholars"].value_counts())
print(c)

0    9413
1     255
5      37
6       7
Name: Vision Scholars, dtype: int64
12


## Export 4

In [113]:
step_up_ex4= pd.read_excel(r"C:\\Users\\Hussam\Desktop\\RT Fisher\\STEP UP Academy student list.xlsx", sheet_name="School Sort")
step_up_ex4_first=step_up_ex4["STUDENT FIRST NAME"].tolist()
step_up_ex4_last = step_up_ex4["STUDENT LAST NAME"].tolist()
step_up_ex4_names=[f+" "+l for f,l in zip(step_up_ex4_first,step_up_ex4_last)]
c=0

for index,row in master_sheet.iterrows():
    name=(row["First Name"]) + " " + (row["Last Name"])
    master_sheet.loc[index,"full name"]=name
    if name in step_up_ex4_names:
        rowIndexes = master_sheet.index[master_sheet["full name"]==name]
        for rowIndex in rowIndexes:
            if master_sheet.loc[rowIndex, "Vision Scholars"]==0:
                master_sheet.loc[rowIndex, 'Vision Scholars'] = 5
            if master_sheet.loc[rowIndex, "Vision Scholars"]==1:
                master_sheet.loc[rowIndex, 'Vision Scholars'] = 6
        c+=1
print(master_sheet["Vision Scholars"].value_counts())
print(c)

0    9412
1     254
5      38
6       8
Name: Vision Scholars, dtype: int64
45


In [114]:
master_sheet.to_excel("vision_step_implemented.xlsx")